
<section>

    <div class="container">
        <div  class="row">
            <!--Banner Principal -->
            <div class="col-sm-12">
                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                    </ol>

                    <!-- Wrapper for slides -->
                    <div class="carousel-inner" role="listbox">
                        <div class="item active">
                            <img src="static/thumbs/banner-cachorro-baby-cao-01.jpg" alt="Baby Cão Foz do Iguaçu">
                            <div class="carousel-caption">

                            </div>
                        </div>
                        <div class="item">
                            <img src="static/thumbs/banner-cachorro-baby-cao-01.jpg" alt="Tudo que seu melhor Amigo Precisa você encontra auqi na Baby Cão">
                            <div class="carousel-caption">

                            </div>
                        </div>
                        <div class="item">
                            <img src="static/thumbs/banner-cachorro-baby-cao-01.jpg" alt="Cliníca Veterinária em Foz do Iguaçu">
                            <div class="carousel-caption">

                            </div>
                        </div>

                    </div>

                    <!-- Controls -->
                    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                        <span class="sr-only">Próximo</span>
                    </a>
                    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        <span class="sr-only">Anterior</span>
                    </a>
                </div>
            </div>
            <!--Banner Principal -->

            <div class="col-sm-12">
                <div class="col-sm-6 BannerFelinos">
                    <h2>Cuidados com Seu Gato</h2>
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/KJTLaDPCo7U"></iframe>
                    </div>
                    <p></p>
                </div>
                <div class="col-sm-6 BannerCaninos">
                    <h2>Cuidados com o Seu Cachorro</h2>
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/KKKJWaVaOco"></iframe>
                    </div>
                    <p></p>
                </div>
            </div>

            <div class="col-sm-12">
                <div class="col-sm-3 BannerAmenidades1">
                    <h1><center><span class="glyphicon glyphicon-search" aria-hidden="true"></span></center></h1>
                    <h2 class="text-center">Pré Atendimento</h2>
                    <p>O Cliente chega ao Hospital e é realizado um cadastro pessoal e também do paciente. Em casos urgentes o paciente é atendido imediatamente.</p>
                </div>
                <div class="col-sm-3 BannerAmenidades2">
                    <h1><center><span class="glyphicon glyphicon-zoom-in" aria-hidden="true"></span></center></h1>
                    <h2 class="text-center">Exame</h2>
                    <p>Após o pré-atendimento o paciente aguarda até que seu nome seja chamado e é encaminhado para médicos especializados no problema em questão. </p>
                </div>
                <div class="col-sm-3 BannerAmenidades3">
                    <h1><center><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></center></h1>
                    <h2 class="text-center">Diagnóstico</h2>
                    <p>O exame e realizado sendo dado o diagnóstico do problema ao responsável, logo após o medico prepara a melhor solução de tratamento para o animal.</p>
                </div>
                <div class="col-sm-3 BannerAmenidades4">
                    <h1><center><span class="glyphicon glyphicon-heart" aria-hidden="true"></span></center></h1>
                    <h2 class="text-center">Tratamento</h2>
                    <p>Com o diagnóstico encontrado, o médico pode iniciar o tratamento no paciente ou receitar os remédios necessários para que possa realizar o tratamento em sua residência.</p>
                </div>
            </div>

        </div>
    </div>

</section>

