<div class="fullwidthbanner-container revolution">
  <div class="fullwidthbanner">
    <ul>


      <?php foreach ($this->banner as $item): ?>
        <li data-transition="fade"> <img src="/static/upload/banner/<?php echo $item['caminho'] ?>"> alt="" />
          <!-- <div class="caption sfb bold text-center" data-x="center" data-y="198" data-speed="900" data-start="800" data-easing="Sine.easeOut">Hello! This is Slowave</div>
          <div class="caption sfb lite small text-center" data-x="center" data-y="258" data-speed="900" data-start="1500" data-easing="Sine.easeOut">A responsive site template with a clean and profession design <br />that will be a great solution for your business, portfolio, blog or any other purpose.</div>
          <div class="caption sfb" data-x="center" data-y="353" data-speed="900" data-start="2200" data-easing="Sine.easeOut"><a href="#" class="btn btn-large">Purchase Now</a></div> -->
        </li>

      <?php endforeach; ?>

    </ul>
    <div class="tp-bannertimer tp-bottom"></div>
  </div>
  <!-- /.fullwidthbanner -->
</div>
<!-- /.fullwidthbanner-container -->

<div class="dark-wrapper">
  <div class="container inner">
    <div class="section-title text-center">
      <h1>O que Fazemos?</h1>
      <span class="icon"><i class="icon-cog-1"></i></span> </div>
    <div class="col-services">
      <div class="row">
        <?php foreach ($this->fazemos as $item): ?>
          <div class="col-sm-4">
            <div class="icon"> <i class="<?php echo $item['icon'] ?> icn"></i> </div>
            <!-- /.icon -->
            <div class="text">
              <h5 class="upper"><?php echo $item['nome'] ?></h5>
              <p><?php echo $item['descricao'] ?></p>
            </div>
            <!-- /.text -->
          </div>

        <?php endforeach; ?>

        <!-- /.col-sm-4 -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.services -->
  </div>
</div>
<div class="black-wrapper">
  <div class="container inner">
    <div class="section-title text-center">
      <h1>Eventos</h1>
      <span class="icon"><i class="icon-picture"></i></span> </div>
            <div class="owl-portfolio owlcarousel carousel-th">
                <?php foreach ($this->eventos as $item): ?>
                    <div class="item">
                        <figure class="icon-overlay medium icn-link"> <a href="/view/interna/id/<?php echo $item['idtipo'] ?>"><img src="/static/upload/images/<?php echo $item['img_destaque'] ?>" alt="" /></a></figure>
                        <div class="image-caption">
                            <h3><a href="/view/interna/id/<?php echo $item['idtipo'] ?>"><?php echo $item['nome'] ?></a></h3>
                            <span class="meta"><?php echo $item['resumo'] ?></span> </div>
                    </div>
                    <?php $link2 = $item['categoria_idcategoria'] ?>
                <?php endforeach; ?>
            </div>
    <!-- /.owlcarousel -->
    <div class="divide50"></div>
      <div class="text-center"> <a class="btn btn-border-light" href="/view/<?php echo $link2?>">Veja todos</a> </div>
  </div>
</div>

<div class="dark-wrapper">
  <div class="container inner">
    <div class="section-title text-center">
      <h1>Ações</h1>
      <span class="icon"><i class="icon-users"></i></span> </div>
    <div class="owl-team owlcarousel carousel-th team">



        <?php foreach ($this->acoes as $item): ?>


            <div class="item">
                <figure> <img src="/static/upload/images/<?php echo $item['img_destaque'] ?>" alt="" /></figure>
                <div class="image-caption">
                    <span class="meta"><?php echo $item['nome'] ?></span>
                    <p><?php echo $item['resumo'] ?></p>
                </div>
            </div>
            <!-- /.item -->
            <?php $link3 = $item['categoria_idcategoria'] ?>
        <?php endforeach; ?>
    </div>
    <!-- /.owlcarousel -->
      <div class="divide50"></div>
      <div class="text-center"> <a class="btn btn-border-light" href="/view/<?php echo $link3?>">Veja todos</a> </div>

  </div>
</div>
<div class="light-wrapper">
  <div class="container inner">
    <div class="section-title text-center bm20">
      <h1>Destaques</h1>
      <span class="icon"><i class="icon-pencil"></i></span> </div>
    <div class="divide30"></div>
    <div class="latest-blog-wrapper">
      <div class="latest-blog">

          <?php foreach ($this->destaques as $item): ?>
              <div class="post">
                  <figure class="icon-overlay medium icn-link"><a href="/view/interna/id/<?php echo $item['idtipo'] ?>"><img src="/static/upload/images/<?php echo $item['img_destaque'] ?>" alt="" /></a></figure>
                  <div class="post-content">
                      <h3 class="post-title"><a href="/view/interna/id/<?php echo $item['idtipo'] ?>"><?php echo $item['nome'] ?></a></h3>
                      <p><?php echo $item['resumo'] ?></p>
                  </div>
              </div>
              <!-- /.item -->
          <?php $link4 = $item['categoria_idcategoria'] ?>
          <?php endforeach; ?>

        </div>
      </div>
    </div>
    <div class="text-center"> <a class="btn btn-border-light" href="/view/<?php echo $link4?>">Veja todos</a> </div>
  </div>
</div>
<div class="dark-wrapper">
  <div class="container inner">
    <div class="section-title text-center">
      <h1>Redes sociais</h1>
      <span class="icon"><i class="icon-globe"></i></span> </div>
    <div class="share text-center"> <a href="#" class="btn share-facebook">Like</a> <a href="#" class="btn share-twitter">Tweet</a> </div>
  </div>
</div>
