<section>

    <div class="container">

        <div class="col-sm-12">
            <h1 class="TitulosPaginas">Problemas Comuns <small>Baby Cão Clínica Veterinária em Foz do Iguaçu</small></h1>

            <div class="list-group col-sm-3">
                <a href="#" class="list-group-item active">Cães</a>
                <a href="exemplo-problema-aberto.html" class="list-group-item">Fraturas</a>
                <a href="exemplo-problema-aberto.html" class="list-group-item">Obesidade</a>
                <a href="exemplo-problema-aberto.html" class="list-group-item">Leptospire</a>
                <a href="exemplo-problema-aberto.html" class="list-group-item">Parvovirose</a>
                <a href="#" class="list-group-item active">Gatos</a>
                <a href="exemplo-problema-aberto.html" class="list-group-item">Giardíase</a>
                <a href="exemplo-problema-aberto.html" class="list-group-item">Dermatofitose</a>
                <a href="exemplo-problema-aberto.html" class="list-group-item">Microplasmose</a>
                <a href="exemplo-problema-aberto.html" class="list-group-item">Lipidose Hepática</a>
            </div>
            <div class="col-sm-9 TitulosPaginas">
                <div class="alert alert-warning TitulosPaginas" role="alert">
                    <p>Confira aqui os problemas de saúde mais recorrentes em animais de estimação.</p>
                </div>
            </div>




        </div>
    </div>

</section>