<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8"/>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport">
    <title>Baby Cão Clínica Veterinária em Foz do Iguaçu</title>

    <META NAME="ROBOTS" CONTENT="NOINDEX, FOLLOW">
    <META NAME="ROBOTS" CONTENT="INDEX, NOFOLLOW">
    <META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">

    <meta name="description" content="Título do Site">
    <meta name="keywords" content="Palavras Chave 1, e 2,3,4...">
    <meta name="author" content="Tiago Guillande">

    <link href="static/css/styles.css" rel="stylesheet"/>

    <!-- Latest compiled and minified CSS -->
    <link href="static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Optional theme -->
    <link rel="stylesheet" href="static/css/bootstrap-theme.min.css" rel="stylesheet">

    <!-- Web Fonts Google -->
    <link href="https://fonts.googleapis.com/css?family=Jaldi:400,700|Open+Sans:300,400,700" rel="stylesheet">


</head>
<body>

<head>
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <h1>
                    <img src="static/thumbs/logo-baby-cao.jpg" title="Baby Cão Clínica Veterinária" alt="Baby Cão Clínica Veterinária" class="LogoBabyCao" width="320px">
                </h1>
            </div>
            <div class="col-sm-8">
                <nav>
                    <ul class="list-unstyled list-inline MenuGeral pull-right">
                        <a href="/"><li class="MenuGeral01 col-sm-2">Página inicial</li></a>
                        <a href="/servicos"><li class="MenuGeral02 col-sm-2">Serviços</li></a>
                        <a href="/prob"><li class="MenuGeral03 col-sm-2">Prob. Comuns</li></a>
                        <a href="/ajuda"><li class="MenuGeral04 col-sm-2">Ajuda</li></a>
                        <a href="/petshop"><li class="MenuGeral05 col-sm-2">PetShop</li></a>
                        <a href="/faleconosco"><li class="MenuGeral06 col-sm-2">Fale Conosco</li></a>
                    </ul>
                </nav>
            </div>
        </div>
    </div><!--/Row -->
</head>

<?php echo $this->layout()->content; ?>

<footer>
    <div class="container">
        <hr>
        <div  class="row">
            <div class="col-sm-12">

                <div class="col-sm-3 RodapeBabyCao">
                    <p><img src="static/thumbs/logo-baby-cao.jpg" title="Baby Cão Clínica Veterinária" alt="Baby Cão Clínica Veterinária" class="LogoBabyCao" width="220px"></p>
                </div>
                <div class="col-sm-3 RodapeBabyCao">
                    <h3>(45) 3523-4243</h3>
                    <p>Rua Castelo Branco, 1091 Centro de Foz do Iguaçu</p>
                </div>
                <div class="col-sm-3 RodapeBabyCao">
                    <ul class="list-unstyled list-inline col-sm-12">
                        <li><a href="#"><img src="static/thumbs/facebook.jpg"></a></li>
                        <li><a href="#"><img src="static/thumbs/whatsapp.jpg"></a></li>
                    </ul>
                </div>
                <div class="col-sm-3 RodapeBabyCao">
                    <nav>
                        <ul class="list-unstyled col-sm-6">
                            <li><a href="index.html">Página inicial</a></li>
                            <li><a href="servicos.html">Serviços</a></li>
                            <li><a href="problemas-comuns.html">Prob. Comuns</a></li>
                        </ul>
                        <ul class="list-unstyled col-sm-6">
                            <li><a href="ajuda.html">Ajuda</a></li>
                            <li><a href="petshop.html">PetShop</a></li>
                            <li><a href="faleconosco.html">Fale Conosco</a></li>
                        </ul>

                    </nav>
                </div>

            </div>
        </div>
    </div>
</footer>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="static/js/bootstrap.min.js"></script>


</body>
</html>