<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<link rel="shortcut icon" href="/static/slowave/style/images/favicon.png">
<title>Slowave</title>
<!-- Bootstrap core CSS -->
<link href="/static/slowave/style/css/bootstrap.css" rel="stylesheet">
<link href="/static/slowave/style/css/settings.css" rel="stylesheet">
<link href="/static/slowave/style/css/owl.carousel.css" rel="stylesheet">
<link href="/static/slowave/style/js/google-code-prettify/prettify.css" rel="stylesheet">
<link href="/static/slowave/style/js/fancybox/jquery.fancybox.css" rel="stylesheet" type="text/css" media="all" />
<link href="/static/slowave/style/js/fancybox/helpers/jquery.fancybox-thumbs.css?v=1.0.2" rel="stylesheet" type="text/css" />
<link href="/static/slowave/style.css" rel="stylesheet">
<link href="/static/slowave/style/css/color/blue.css" rel="stylesheet">
<link href='http://fonts.googleapis.com/css?family=Raleway:400,300,500,600,700,800,900' rel='stylesheet' type='text/css'>
<link href="/static/slowave/style/type/fontello.css" rel="stylesheet">
<link href="/static/slowave/style/type/picons.css" rel="stylesheet">
<link href="/static/slowave/style/type/budicons.css" rel="stylesheet">
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="/static/slowave/style/js/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
      <![endif]-->
</head>
<body class="full-layout">
<div class="body-wrapper">
  <div class="yamm navbar basic default">
    <div class="navbar-header">
      <div class="container">
        <div class="basic-wrapper">
          <!-- <a class="btn responsive-menu pull-right" data-toggle="collapse" data-target=".navbar-collapse"><i class='icon-menu-1'></i></a> -->
          <a class="navbar-brand" href="index.html"><img src="/static/upload/Fiep.png" data-at2x="/static/slowave/style/images/logo@2x.png" alt="" width="100px"/></a>
        </div>
        <div class="collapse navbar-collapse pull-right">
          <ul class="nav navbar-nav">
            <?php foreach ($this->atividades as $item): ?>
                <li class="dropdown"><a href="#" class="dropdown-toggle js-activated"> <?php echo $item['nome'] ?></a>
                    <ul class="dropdown-menu">
                      <?php foreach ($this->atividades1 as $item1): ?>
                          <?php if ($item1['categoria_idcategoria'] == $item['idcategoria']){?>
                              <li><a href="index.html"><?php echo $item1['nome'] ?></a></li>
                          <?php } ?>
                    <?php endforeach; ?>
                    </ul>

                </li>
            <?php endforeach; ?>

          </ul>
        </div>
      </div>
    </div>
    <!--/.nav-collapse -->
  </div>
  <!--/.navbar -->
  <div class="offset"></div>

  <?php echo $this->Layout()->content; ?>

  <footer class="black-wrapper">
    <div class="container inner">
      <div class="row">
        <div class="col-sm-3">
          <div class="widget"> <img src="/static/upload/Fiep.png" data-at2x="/static/slowave/style/images/logo@2x.png" alt="" width="25%"/>
            <div class="divide20"></div>
            <p>Aenean lacinia bibendum nulla sed leo posuere erat a ante venenatis dapibus posuere velit aliquet. Donec ullamcorper metus auctor fringi. Nullam quis risus. </p>
            <p>Vestibulum id ligula porta  euismod semper. Maecenas faucibus mollis.</p>
            <div class="divide5"></div>
            <ul class="social">
              <li><a href="#"><i class="icon-s-rss"></i></a></li>
              <li><a href="#"><i class="icon-s-twitter"></i></a></li>
              <li><a href="#"><i class="icon-s-facebook"></i></a></li>
              <li><a href="#"><i class="icon-s-pinterest"></i></a></li>
              <li><a href="#"><i class="icon-s-linkedin"></i></a></li>
            </ul>
          </div>
          <!-- /.widget -->
        </div>
        <!-- /col -->

        <div class="col-sm-3">
          <div class="widget">
            <h3 class="section-title widget-title upper">Popular Posts</h3>
            <ul class="post-list">
              <li>
                <h6><a href="blog-post.html">Vivamus sagittis lacus vel augue metus</a></h6>
                <em>3th Oct 2012</em> </li>
              <li>
                <h6><a href="blog-post.html">Scelerisque nisl consectetur et</a></h6>
                <em>28th Sep 2012</em> </li>
              <li>
                <h6><a href="blog-post.html">Pellentesque ornare sem lacinia quam</a></h6>
                <em>15th Aug 2012</em> </li>
            </ul>
            <!-- /.post-list -->
          </div>
          <!-- /.widget -->
        </div>
        <!-- /col -->

        <div class="col-sm-3">
          <div class="widget">
            <h3 class="section-title widget-title upper">Get In Touch</h3>
            <p>Fusce dapibus, tellus commodo, tortor mauris condimentum utellus fermentum, porta sem malesuada magna. Sed posuere consectetur est at lobortis.</p>
            <div class="divide10"></div>
            <div class="contact-info"> <i class="icon-location"></i> Moonshine St. 14/05 Light City <br />
              <i class="icon-phone"></i>+00 (123) 456 78 90 <br />
              <i class="icon-mail"></i> <a href="first.last@email.com">first.last@email.com</a> </div>
          </div>
        </div>
        <!-- /col -->

        <div class="col-sm-3">
          <div class="widget">
            <h3 class="section-title widget-title upper">Tags</h3>
            <div class="tagcloud"> <a href="#" style="font-size: 9pt;">blogroll</a> <a href="#" style="font-size: 19pt;">daily</a> <a href="#" style="font-size: 9pt;">dialog</a> <a href="#" style="font-size: 9pt;">gallery</a> <a href="#" style="font-size: 10pt;">journal</a> <a href="#" style="font-size: 9pt;">link</a> <a href="#" style="font-size: 12pt;">motion</a> <a href="#" style="font-size: 9pt;">music</a> <a href="#" style="font-size: 20pt;">photo</a> <a href="#" style="font-size: 13pt;">professional</a> <a href="#" style="font-size: 16pt;">quotation</a> <a href="#" style="font-size: 9pt;">show</a> <a href="#" style="font-size: 15pt;">sound</a> <a href="#" style="font-size: 9pt;">tv</a> <a href="#" style="font-size: 9pt;">video</a> <a href="#" style="font-size: 9pt;">gift</a> <a href="#" style="font-size: 19pt;">label</a> <a href="#" style="font-size: 9pt;">christmas</a> </div>
          </div>
          <!-- /.widget -->
          <div class="divide30"></div>
          <div class="widget">
            <h3 class="section-title widget-title upper">Newsletter</h3>
            <form id="newsletter" class="form-inline newsletter" role="form">
              <div>
                <label class="sr-only" for="exampleInputEmail">Email address</label>
                <input type="email" class="form-control" id="exampleInputEmail" placeholder="Enter email">
              </div>
              <button type="submit" class="btn btn-default btn-submit"><i class="icon-paper-plane"></i></button>
            </form>
          </div>
          <!-- /.widget -->

        </div>
        <!-- /col -->
      </div>
      <!-- /.row -->
    </div>
    <!-- .container -->

    <div class="sub-footer">
      <div class="container">
        <p class="pull-left">© 2014 Slowave. All rights reserved. Theme by <a href="http://elemisfreebies.com">elemis</a>.</p>
        <ul class="footer-menu pull-right">
          <li><a href="#">Home</a></li>
          <li><a href="#">About</a></li>
          <li><a href="#">Portfolio</a></li>
          <li><a href="#">Blog</a></li>
          <li><a href="#">Contact</a></li>
        </ul>
      </div>
    </div>
  </footer>
  <!-- /footer -->

</div>
<!-- /.body-wrapper -->
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/static/slowave/style/js/jquery.min.js"></script>
<script src="/static/slowave/style/js/bootstrap.min.js"></script>
<script src="/static/slowave/style/js/twitter-bootstrap-hover-dropdown.min.js"></script>
<script src="/static/slowave/style/js/jquery.themepunch.plugins.min.js"></script>
<script src="/static/slowave/style/js/jquery.themepunch.revolution.min.js"></script>
<script src="/static/slowave/style/js/jquery.fancybox.pack.js"></script>
<script src="/static/slowave/style/js/fancybox/helpers/jquery.fancybox-thumbs.js?v=1.0.2"></script>
<script src="/static/slowave/style/js/fancybox/helpers/jquery.fancybox-media.js?v=1.0.0"></script>
<script src="/static/slowave/style/js/jquery.isotope.min.js"></script>
<script src="/static/slowave/style/js/jquery.easytabs.min.js"></script>
<script src="/static/slowave/style/js/owl.carousel.min.js"></script>
<script src="/static/slowave/style/js/jquery.fitvids.js"></script>
<script src="/static/slowave/style/js/google-code-prettify/prettify.js"></script>
<script src="/static/slowave/style/js/jquery.slickforms.js"></script>
<script src="/static/slowave/style/js/retina.js"></script>
<script src="/static/slowave/style/js/scripts.js"></script>
</body>
</html>
