<!DOCTYPE html>
<!--[if IE 8]> 				 <html class="no-js lt-ie9" lang="en" > <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en" > <!--<![endif]-->

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Uniamérica</title>
    <link rel="stylesheet" href="/foundation/css/normalize.css" />
    <link rel="stylesheet" href="/foundation/css/foundation.css" />
    <script src="/foundation/js/vendor/custom.modernizr.js"></script>
    <script src="/foundation/js/vendor/jquery.js"></script>

    <script src="/global/global.js"></script>

    <script src="/global/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="/global/jquery-validation/dist/additional-methods.js"></script>
    <script src="/global/jquery.maskedinput.min.js"></script>
    <link rel="stylesheet" href="/vestibular-2013-bolsas/styles/main.css">
    <script src="/vestibular-2013-bolsas/scripts/vendor/modernizr.js"></script>

    <link href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" media="screen" rel="stylesheet" type="text/css" >
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <script src="/global/jquery-ui/js/jquery.ui.datepicker-pt-BR.js"></script>


<style type="text/css" media="all">
html, body {
 height:100%;
}
* html #tudo {
 height: 100%;
}
body {
 margin:0;
 padding:0;
}
#layout {
 position:relative;
 width:100%;
 min-height:100%;
 background-color:#fff;
}

#conteudo {
 padding-bottom:30px;
 background-color:#fff;
 width:100%;
 margin:0 auto;
}
#topo {
 background:#628114 url("http://uniamerica.br/static/inscricoes/img/header.jpg") center center no-repeat;
 display:block;
 width:100%;
 height:165px;
 margin:0 auto
}

#principal {

 width:100%;
 padding-bottom:107px;
 margin:0 auto;

}
#rodape {
 background:#628114 url("http://www.uniamerica.br/static/inscricoes/img/footer.jpg") center center no-repeat;
 width:100%;
 height:99px;
 margin:0 auto;
 position: absolute;
 bottom: 0;

}
.header-inner {
    width: 826px;
    margin: 0 auto;
}
.header-inner .social-network {
    float: right;
    margin-top: 5px;

}
.nav-header {
    color: #004920;
    font-family: 'Open Sans Condensed',arial;
    font-size: 20px;
    left: 222px;
    position: relative;
    top: 72px;
}
.nav-header a {
    color: #004920;
    text-decoration: none;
}

</style>

</head>
<body>

<div id="layout">
    <div id="conteudo">
    <div id="topo">
        <div class="header-inner">
            <div class="social-network">
                <!-- BEGIN PHP Live! code, (c) OSI Codes Inc. -->
                <script language="JavaScript" src="http://chat.uniamerica.br/js/status_image.php?base_url=http://chat.uniamerica.br&l=atendimento&x=1&deptid=4&"><a href="http://www.phplivesupport.com"></a></script>
                <!-- END PHP Live! code : (c) OSI Codes Inc. -->
                <a target="_new" href="https://www.facebook.com/FaculdadeUniamerica/"><img title="Acompanhe-nos no Facebook" alt="Facebook" src="/static/inscricoes/img/ico-face.png"></a>
                <a target="_new" href="http://www.youtube.com/uniamerica/"><img title="Acompanhe-nos no Youtube" alt="Youtube" src="/static/inscricoes/img/ico-youtube.png"></a>
            </div>
            <div class="nav-header">
                <a href="http://www.uniamerica.br/vestibular/">HOME</a>
            </div>
        </div>
    </div>
    <div id="principal">

            <?php echo $this->layout()->content; ?>



</div>
<!-- Fim #principal -->



</div>
<!-- Fim #conteudo -->
<div id="rodape">
</div>
</div>


<script src="/foundation/js/foundation.min.js"></script>
<script>
$(document).foundation();
</script>
<!-- Google Code for matricula Conversion Page -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 982590914;
var google_conversion_language = "en";
var google_conversion_format = "2";
var google_conversion_color = "ffffff";
var google_conversion_label = "8zaGCKbujgYQwsvE1AM";
var google_conversion_value = 0;
var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/982590914/?value=0&amp;label=8zaGCKbujgYQwsvE1AM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>

</body>
</html>

