<!DOCTYPE html>
<!--[if IE 8]> 				 <html class="no-js lt-ie9" lang="en" > <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en" > <!--<![endif]-->

    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <title>Uniamérica</title>
        <link rel="stylesheet" href="/foundation/css/normalize.css" />
        <link rel="stylesheet" href="/foundation/css/foundation.css" />
        <script src="/foundation/js/vendor/custom.modernizr.js"></script>
        <script src="/foundation/js/vendor/jquery.js"></script>

        <script src="/global/global.js"></script>

        <script src="/global/jquery-validation/dist/jquery.validate.min.js"></script>
        <script src="/global/jquery-validation/dist/additional-methods.js"></script>
        <script src="/global/jquery.maskedinput.min.js"></script>
        <link rel="stylesheet" href="/vestibular-2013-bolsas/styles/main.css">
        <script src="/vestibular-2013-bolsas/scripts/vendor/modernizr.js"></script>

        <link href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" media="screen" rel="stylesheet" type="text/css" >
        <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
        <script src="/global/jquery-ui/js/jquery.ui.datepicker-pt-BR.js"></script>


        <style type="text/css" media="all">
            @media (max-width: 767px){
            .container {
                width: 480px;
            }
            #topo {
                background: #2d3541 url("http://uniamerica.br/static/inscricoes/img/header_pos.png") -100px no-repeat !important;
            }
            #layout {
                width: 500px !important; 
            }
            #conteudo {
                width: 500px !important;
            }
            }
            html, body {
                height:100%;
            }
            * html #tudo {
                height: 100%;
            }
            body {
                margin:0;
                padding:0;
            }
            #layout {
                position:relative;
                width:100%;
                min-height:100%;
                background-color:#fff;
            }

            #conteudo {
                padding-bottom:30px;
                background-color:#fff;
                width:100%;
                margin:0 auto;
            }
            #topo {
                background:#2d3541 url("/static/inscricoes/img/header_pos.png") center center no-repeat;
                display:block;
                width:100%;
                height:165px;
                margin:0 auto
            }

            #principal {

                width:100%;
                padding-bottom:107px;
                margin:0 auto;

            }
            #rodape {
                background:#2d3541 url("/static/inscricoes/img/footer_pos.png") center center no-repeat;
                width:100%;
                height:99px;
                margin:0 auto;
                position: absolute;
                bottom: 0;

            }

            .header-inner {
                width: 50%;
                margin: 0 auto;
            }
            .header-inner .social-network {
                float: right;
                margin-top: 5px;

            }
            .nav-header {
                color: #004920;
                font-family: 'Open Sans Condensed',arial;
                font-size: 20px;
                left: 222px;
                position: relative;
                top: 72px;
            }
            .nav-header a {
                color: #CC9B00;
                text-decoration: none;
            }
            .navbar {
                background: #c55a34;
                border-radius: 10px;
            }
        </style>

    </head>
    <body>
        <!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-NFF9VV"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-NFF9VV');</script>
<!-- End Google Tag Manager -->
        <div id="layout">
            <div id="conteudo">
                <div id="topo">
                    <div class="header-inner">
                        <div class="social-network">
                            <!-- BEGIN PHP Live! code, (c) OSI Codes Inc. -->
                            <script language="JavaScript" src="http://chat.uniamerica.br/js/status_image.php?base_url=http://chat.uniamerica.br&l=atendimento&x=1&deptid=4&">
                                < a href = "http://www.phplivesupport.com" > < /a>
                                                    </script>
                            <!-- END PHP Live! code : (c) OSI Codes Inc. -->
                            <a target="_new" href="https://www.facebook.com/FaculdadeUniamerica/"><img title="Acompanhe-nos no Facebook" alt="Facebook" src="/static/inscricoes/img/ico-face.png"></a>
                            <a target="_new" href="http://www.youtube.com/uniamerica/"><img title="Acompanhe-nos no Youtube" alt="Youtube" src="/static/inscricoes/img/ico-youtube.png"></a>
                        </div>
                        <div class="nav-header">
                            <a href="http://www.uniamerica.br/pos/">HOME</a>
                        </div>
                    </div>
                </div>
                <div id="principal">

                    <?php echo $this->layout()->content; ?>



                </div>
                <!-- Fim #principal -->



            </div>
            <!-- Fim #conteudo -->
            <div id="rodape">
            </div>
        </div>


        <script src="/foundation/js/foundation.min.js"></script>
        <script>
                    $(document).foundation();
        </script>
        
    </body>
</html>