<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Logar Admin</title>

    <!-- Bootstrap core CSS -->
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.css" />

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="/static/css/login.css" />
  </head>

  <body class="text-center">
    <div class="form-signin">
      <img class="mb-4" src="/static/upload/FIEP.png" alt="" width="150">
      <?php echo $this->form; ?>
			<?php if( $this->error ): ?>
					<div class='notification'>
						<p><?php echo $this->error; ?></p>
					</div>
			<?php endif; ?>
    </div>
  </body>
</html>
