<html>
    <head>
        <title>Relatório</title>
        <meta charset="utf-8">
        <style type="text/css">
            *{
                margin: 0;
                padding: 0;
            }
            body {
                background: #F3F3F3;
                font-family: "Myriad Pro", helvetica, sans-serif;
            }

            form {
                text-align: center;
                width: 90%;
                padding: 2% 2% 2% 2%;
                margin: 10px auto;
                text-shadow: 0 1px 0px rgba(255, 255, 255, 0.8);

            }
            form input {
                margin: 10px;
            }
            form p {
                color:red;
            }

            form input[type=submit]{
                background-color: #7fbf4d;
                border: 1px solid #63a62f;
                border-bottom: 1px solid #5b992b;
                border-radius: 3px;
                color: #fff;
                padding: 5px 0 5px 0;
                text-align: center;
                text-shadow: 0 -1px 0 #4c9021;
                width: 100px;
            }
            article {
                border-radius: 5px;
                width: 90%;
                padding: 2% 2% 2% 2%;
                box-shadow: 5px 5px 15px #ccc;
                margin: 100px auto;
                text-shadow: 0 1px 0px rgba(255, 255, 255, 0.8);
                background: fff;  
            }
            header {
                text-align: center;
                line-height: 4;
            }
            table {
                width: 100%;
            }
            table tr {

                line-height: 2;
            }
            table tr:nth-child(odd){
                background: #DDDDDD;
            }
            table tr:hover{
                background:#d4f2a6;
                cursor: pointer;
            }
            .titulo {
                background-color: #000;
                color: fff;
                text-align: center;
            }
            footer {
                text-align: left;
                padding: 10px;
                line-height: 2;
                border-top: 1px #DDDDDD solid;
            }
            footer p {
                color: forestgreen;
            }
        </style>
    </head>
    <body>
        <form metod="post" method="post">
            <label for="login">Usuário</label><input id="login" type="text" name="login">
            <label for="senha">Senha</label><input id="senha" type="password" name="senha">
            <input type='submit' value="Listar">
            <?php
            $login = "congresso";
            $senha = "Cbi08mio";

            if (@$_POST['login'] <> "") {
                if (
                        $_POST['login'] === $login && $_POST['senha'] === $senha) {
                    ?>
                    <article>
                        <header>
                            <img src='http://uniamerica.br/static/congresso/img/logo.png' >
                            <h1>Ralatório de inscrição</h1>
                        </header>
                        <table>
                            <td class="titulo">Nome</td>
                            <td class="titulo">Email</td>
                            <td class="titulo">Residencia</td>
                            <td class="titulo">Comercial</td>
                            <td class="titulo">Celular</td>
                            <td class="titulo">Boleto</td>
                            <td class="titulo">Cartão</td>
                            <?php
                            $vboleto = 0;
                            $vcartao = 0;
                            foreach ($this->boleto as $item):
                                $vboleto += $item['boleto'];
                                $vcartao += $item['cartao'];
                                ?>
                                <tr>
                                    <td><?php echo $item['nome'] ?></td>
                                    <td><?php echo $item['email'] ?></td> 
                                    <td><?php echo $item['telres'] ?></td>
                                    <td><?php echo $item['telcom'] ?></td>
                                    <td><?php echo $item['telcel'] ?></td>
                                    <td><?php echo number_format(($item['boleto'] / 100), 2, ",", ".") ?></td>
                                    <td><?php echo number_format(($item['cartao'] / 100), 2, ",", ".") ?></td>
                                </tr>
                            <?php endforeach; ?>
                        </table>
                        <footer>
                            
                                <p><strong><?php echo count($this->boleto); ?></strong> inscritos até o momento</p>
                                <p>Total pago boleto: <?php echo number_format(($vboleto / 100), 2, ",", ".") ?></p>
                                <p>Total pago cartão: <?php number_format(($vcartao / 100), 2, ",", ".") ?></p>
                                <hr>
                                <p><strong>Total geral: <?php echo number_format((($vboleto + $vcartao) / 100), 2, ",", ".") ?></strong></p>
                        </footer>
                    </article>

                    <?php
                } else {
                    //caso contrario, mostra mensagem
                    echo "<p>Dados não conferem!</p>";
                }
            }
            ?>
        </form>
    </body>
</html>