<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
       	<?php echo $this->headTitle(); ?>
        <!-- include jquery -->
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>

        <!-- include libraries BS -->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.css" />
        <script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.5/umd/popper.js"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.js"></script>


    </head>
    <body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <?php if( $this->authStatus ): ?>
                <ul class="sidebar-nav">
                    <li class="sidebar-brand">
                        <a href="#">
                            Fiep
                        </a>
                    </li>
                    <li>
                        <a href="/admin/banner">Banner</a>
                    </li>
                    <li>
                        <a href="/admin/categoria">Categoria</a>
                    </li>
                    <li>
                        <a href="/admin/subcategoria">SubCategoria</a>
                    </li>
                    <li>
                        <a href="/admin/quemsomos">Quem Somos?</a>
                    </li>

                    <li>
                        <a href="#"></a>
                    </li>
                    <li>
                    <a href="<?php echo $this->baseUrl('/admin/auth/logout'); ?>" class="btn">
                        <span class="icon-off"></span> Sair
                    </a>
                    </li>
                </ul>

            <?php endif; ?>
        </div>
        <!-- /#sidebar-wrapper -->
                    <?php echo $this->Layout()->content; ?>
        </div>

        <!-- include summernote -->
        <link rel="stylesheet" href="/static/js/summernote-master/dist/summernote-bs4.css">
        <script type="text/javascript" src="http://localhost/static/js/summernote-master/dist/summernote-bs4.js"></script>

        <link rel="stylesheet" href="example.css">
        <script type="text/javascript">
          $(function() {
            $('.summernote').summernote({
              height: 200,
            });

            $('form').on('submit', function (e) {
              e.preventDefault();
              alert($('.summernote').summernote('code'));
            });
          });
        </script>
    </body>
</html>
