<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
       	<?php echo $this->headTitle(); ?>
        <!-- include jquery -->
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>

        <!-- include libraries BS -->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.css" />
        <link rel="stylesheet" href="/static/css/admin.css" />
        <script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.5/umd/popper.js"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.js"></script>



    </head>
      <?php if( $this->authStatus ): ?>
    <body>

      <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#"><img src="/static/upload/Fiep.png" alt="" width="60" height="60"> FIEP </a>
        <ul class="navbar-nav px-3">
          <li class="nav-item text-nowrap">
            <a class="nav-link" href="<?php echo $this->baseUrl('/admin/auth/logout');?> ">Logout</a>
          </li>
        </ul>
      </nav>

            <div style="margin-top: 10px;"class="container-fluid">
              <div class="row">

                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                  <div style="margin-top: 10px;" class="sidebar-sticky">
                    <ul class="nav flex-column">

                        <li class="nav-item">
                            <a class="nav-link" href="/admin/banner">

                                Banner
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/admin/categoria">

                                Menu - Categorias
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/admin/subcategoria">

                                Menu - SubCategoria
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/admin/footer">
                                Footer
                            </a>
                        </li>

                        <?php foreach ($this->menu as $item): ?>
                            <li class="nav-item">
                                <a class="nav-link active" href="/admin/categoria/<?php echo $item['idcategoria'] ?>">
                                    <span data-feather="home"></span>
                                    <?php echo $item['nome'] ?>
                                </a>
                            </li>

                        <?php endforeach; ?>

                    </ul>
                  </div>
                </nav>
                <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
                          <?php echo $this->Layout()->content; ?>

                </main>
              </div>
            </div>

    </body>
  <?php else: ?>
    <?php echo $this->Layout()->content; ?>
  <?php endif; ?>
</html>
