<style> 
    .mensagem
    {
        text-shadow: 0px 1px 0px #ccc;
        border-radius: 10px;
        margin-top: 10px;
        line-height: 2;
        background:#5e9e2e;
        color: #FFF;
        width:100%;
        height:38px;
    }
</style>
<div class="container-12">
    <div class="grid-12">
        <h1> NORMAS </h1>
        <!-- <div class="mensagem">
            <center>
                <h2>A data de envio de trabalhos foi prorrogada até o dia 28/09. Envie seu trabalho, participe!</h2>
            </center>
        </div>-->
    </div>
    <div class="gred-12 grid-12 list">
        <font>
        Para efetivar a inscrição de trabalhos é necessária a escolha, obrigatoriamente, de um dos eixos temáticos abaixo:
        </font>

        <p><strong>Eixo 1:</strong> Novas abordagens nas pesquisas sobre Políticas Educacionais e Avaliação em larga escala.</p>
        <p><strong>Eixo 2:</strong> Modalidades de Ensino (EJA, Ed. Especial, Ed. Indígena, EAD, etc).</p>
        <p><strong>Eixo 3:</strong> Infância, Linguagem e Produção Cultural.</p>
        <p><strong>Eixo 4:</strong> Tecnologias e Inovações no Ensino.</p>
        <p><strong>Eixo 5:</strong> Avaliação Escolar e Currículo: Desafios Contemporâneos.</p>
        <p><strong>Eixo 6:</strong> Gestão Escolar e Formação Docente: requisitos atuais.</p>
        <br>
        <h3>PROCEDIMENTOS PARA FORMATAÇÃO E APRESENTAÇÃO DOS TRABALHOS CIENTÍFICOS</h3>
        <p>O TRABALHO CIENTÍFICO é composto por um Texto Completo. O teor da Comunicação deve estar vinculado ao conteúdo do Trabalho Científico.</p>
        <p>O autor deverá escolher um dos eixos temáticos do evento para inscrever o seu trabalho.</p>
        <p>Todos os trabalhos devem ser enviados no formato Microsoft Office Word nomeado da seguinte forma: Número do eixo, underline, título da obra em minúsculo. </p>
        <p>Exemplo: Eixo1_política educacional no Brasil.doc</p>
        <p>O trabalho deve ser enviado para o e-mail congresso@uniamerica.br</p>
        <br>
        <h3>NORMAS PARA A REDAÇÃO DO TRABALHO CIENTÍFICO</h3>
        <p>O texto completo para publicação deverá ter o mínimo de 10 e o máximo de 15 páginas, incluindo o resumo.</p>
        <p>Formatação: Papel em formato A4 (21cm x 29,7cm);
            <br>Margens superior e esquerda: 3,00 cm e inferior e direita: 2,00 cm.
            <br>Fonte: Arial, tamanho 12;
            <br>Espaço entre linhas 1,5 – justificado.
        </p>
        <p>Título: negrito, centralizado, letra maiúscula.,em espaço simples. Nomes dos autores: alinhados à direita, dois enter abaixo do título, escritos em negrito, apenas as iniciais maiúsculas. Quando houver mais de um autor, colocar um abaixo do outro com espaço simples. Informações sobre os autores: instituição, titulação e e-mail, em nota de rodapé.</p>
        <p>Resumo: quatro enter abaixo dos nomes dos autores, parágrafo justificado. Escrever a palavra “RESUMO” em letra maiúscula e sem negrito, separada do texto por um espaço. Palavras-chave: mínimo 3, escritas logo abaixo do resumo, após um espaçamento, separadas por vírgula. Escrever “Palavras-chave” em letra maiúscula, sem negrito.</p>
        <p>Referências: Arial 12, espaço simples na referencia e 1,5 cm entre as outras referências, alinhadas à esquerda e organizadas segundo normas da ABNT.</p>
        <p>Exemplos: MARTINS, C. E. Globalização, dependência e neoliberalismo na América Latina. São Paulo: Boitempo, 2011.</p>
        <p>Citações: até 5 linhas, na continuidade do parágrafo. Com mais de 5 linhas, em linha separada, letra menor, espaço simples e recuo de 4cm, conforme ABNT e dois separando do restante do texto.</p>
        <br>
        <h3>NORMAS PARA APRESENTAÇÃO DA COMUNICAÇÃO</h3>
        <p>Cada trabalho terá o tempo máximo para apresentação de 15 minutos, com mais 10 minutos para discussões;</p>
        <p>O uso de equipamento multimídia é opcional;</p>
        <p>Na apresentação devem constar os nomes dos pesquisadores, Instituição a qual estão vinculados, bem como apresentação da pesquisa e resultados alcançados;</p>
        <p>Só serão permitidos para a apresentação, os pesquisadores que estiverem constando do TRABALHO CIENTÍFICO.</p>
        <br>
        <h3>OBSERVAÇÕES IMPORTANTES</h3>
        <ul>
            <li>1. Os trabalhos serão apreciados levando-se em consideração a adequação ao eixo temático, objetividade, clareza, rigor científico, contribuição ao campo de pesquisa e respeito às normas solicitadas;</li>
            <li>2. Os trabalhos que não estiverem dentro desses requisitos serão indeferidos;</li>
            <li>3. A correção gramatical é de responsabilidade dos autores. O excesso de erros indefere o trabalho;</li>
            <li>4. O conteúdo dos trabalhos é de inteira responsabilidade dos autores;</li>
            <li>5. São permitidos até 4 autores em cada trabalho. Todos devem pagar a taxa de inscrição. Caso haja alguma falta de pagamento, o trabalho será indeferido e não haverá devolução dos valores pagos;</li>
            <li>6. Cada autor pode apresentar até 05 (cinco) trabalhos;</li>
            <li>7. Caso haja indeferimento do trabalho, os autores poderão participar como ouvintes;</li>
            <li>8. O Certificado de participação será dado àqueles que completarem o mínimo de 75% da carga horária do evento totalizando 40 horas de participação;</li>
            <li>9. O Certificado de Apresentação de Trabalho só será emitido após a apresentação do mesmo e apenas aos pesquisadores que estiverem presentes na apresentação que receberão;</li>
            <li>10. O Certificado de ouvinte será emitido no prazo no máximo de um mês após a realização do evento e poderá ser retirado na secretaria da Faculdade.</li>
            <li>11. Os anais do evento serão disponibilizados para download no próprio site.</li>
            <li>12. O prazo para envio dos artigos científicos é até o dia 28 de setembro pelo e-mail congresso@uniamerica.br </li>
        </ul>
    </div>

</div>