<div id="page-content-wrapper">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<form action="" role="form" class="form-horizontal" id="form" method="post" enctype="multipart/form-data">
					<fieldset>

						<legend>Video</legend>

						<!-- Text input-->
						<div class="form-group">
							<label class="col-md-4 control-label" for="nome">Nome</label>
							<div class="col-md-4">
								<input id="nome" name="nome" type="text" placeholder="" class="form-control input-md">

							</div>
						</div>
						<br>

						<!-- Text input-->
						<div class="form-group">
							<label class="col-md-4 control-label" for="caminho">Caminho</label>
							<div class="col-md-4">
								<input id="caminho" name="caminho" type="text" placeholder="" class="form-control input-md">

							</div>
						</div>
						<br>
						<div class="form-group">
							<label class="col-md-4 control-label" for="caminho"></label>
							<div class="col-md-4">
								<button type="submit" id="" name="" class="btn btn-primary">Enviar</button>
							</div>
						</div>
					</fieldset>
				</form>
			</div>

			<div class = "col-lg-12">
				<table class="table table-hover table-inverse">
					<thead>
					<tr>
						<th>#</th>
						<th>Nome</th>
						<th>Caminho</th>
						
						<th>Ação</th>
					</tr>
					</thead>
					<tbody>
					<?php foreach ($this->atividades as $item): ?>
						<tr>
							<th scope="row"><?php echo $item['idvideo'] ?></th>
							<td><?php echo $item['nome'] ?></td>
							<td><iframe width="150" class="embed-responsive-item" src="https://www.youtube.com/embed/<?php echo $item['caminho'] ?>"></iframe></td>

							<td><a href="video/excluir/id/<?php echo $item['idvideo'];?>"><button type="button" class="btn btn-danger">Excluir</button></a></td>
						</tr>
					<?php endforeach; ?>

					</tbody>
				</table>

			</div>
		</div>
	</div>
</div>