	<div class="grid-12">
		<div class="sucesso" style="text-align: center;">
			<h3>Você efetuou o seu cadastro com sucesso!</h3>
			<p>Em até 5 dias úteis, após a data de efetuação do seu pagamento, enviaremos  um e-mail de confirmação. 
				<br> Fique atento com a sua caixa de SPAM!</p>
			<p>Qualquer dúvida envie um e-mail para congresso@uniamerica.br</p>
			<p>Agradecemos a sua participação!</p>
			<p>Confira a nossa programação <a href="<?php echo $this->url(array('controller' => 'congresso', 'action' => 'programacao',), null, true) ?>" target="blank_">aqui!</a></p>
		</div>
	</div>