<h3>Contato Uniamérica.</h3>
<pre>
Olá {nome_de}

Informamos que sua inscrição esta quase completa, segue abaixo os dados para pagamento do boleto:

<a href="http://www.uniamerica.com.br/workshopbio/inscricoes/pagamento/chave/{hash}">http://www.uniamerica.com.br/workshopbio/inscricoes/pagamento/chave/{hash}</a>

Caso seu gerenciador de e-mails bloqueie o link em mensagens HTML, copie o endereço abaixo e cole no campo destino ao endereço de páginas:

http://www.uniamerica.com.br/workshopbio/inscricoes/pagamento/chave/{hash}

Atenciosamente Uniamérica.

</pre>