<section>

    <div class="container">

        <div class="col-sm-12">
            <h1 class="TitulosPaginas">Entre em contato <small>Baby Cão Clínica Veterinária em Foz do Iguaçu</small></h1>
            <hr>


            <div class="row">

                <div class="col-md-6">

                    <form>
                        <div class="form-group">
                            <label for="nome">Nome Completo</label>
                            <input type="text" class="form-control" id="nome" placeholder="Nome Completo">
                        </div>
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" id="email" placeholder="seuemail@provedor.com.br">
                        </div>
                        <div class="form-group">
                            <label for="telefone">Telefone</label>
                            <input type="text" class="form-control" id="telefone" placeholder="Telefone">
                        </div>
                        <div class="form-group">
                            <label for="telefone">Mensagem</label>
                            <textarea class="form-control" rows="6"></textarea>
                        </div>


                        <button type="submit" class="btn btn-default">Enviar Contato</button>
                    </form>

                </div>

                <div class="col-md-6">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3600.0932136716146!2d-54.58125488498374!3d-25.53527178374004!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94f6904fa66ed2d5%3A0x1c73067ae9be372!2sR.+Castelo+Branco%2C+1091+-+Vila+Maracana%2C+Foz+do+Igua%C3%A7u+-+PR%2C+85852-010!5e0!3m2!1spt-BR!2sbr!4v1473354790446" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
                </div>


            </div>








        </div>
    </div>

</section>