<div id="page-content-wrapper">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<form action="" role="form" class="form-horizontal" id="form" method="post" enctype="multipart/form-data">
					<fieldset>

						<!-- Form Name -->
						<legend>Banner</legend>

						<!-- Text input-->
						<div class="form-group">
							<label class="col-md-4 control-label" for="Nome">Nome</label>
							<div class="col-md-4">
								<input id="Nome" name="nome" type="text" placeholder="Nome" class="form-control input-md" required="">

							</div>
						</div>

						<!-- File Button -->
						<div class="form-group">
							Selecione uma imagem: <input name="arquivo" type="file" />
							<br />

						</div>
						<div class="form-group">
							<label class="col-md-4 control-label" for="imagem"></label>
							<div class="col-md-4">
								<button type="submit" id="" name="" class="btn btn-primary">Enviar</button>
							</div>
						</div>
					</fieldset>
				</form>
			</div>

			<div class = "col-lg-12">
				<table class="table table-hover table-inverse">
					<thead>
					<tr>
						<th>#</th>
						<th>Nome</th>
						<th>Caminho</th>
						
						<th>Ação</th>
					</tr>
					</thead>
					<tbody>
					<?php foreach ($this->atividades as $item): ?>
						<tr>
							<th scope="row"><?php echo $item['idbanner'] ?></th>
							<td><?php echo $item['nome'] ?></td>
							<td><img width="150" src="/static/upload/banner/<?php echo $item['caminho'] ?>"></td>

							<td><a href="banner/excluir/id/<?php echo $item['idbanner'];?>"><button type="button" class="btn btn-danger">Excluir</button></a></td>
						</tr>
					<?php endforeach; ?>

					</tbody>
				</table>

			</div>
		</div>
	</div>
</div>