<div id="page-content-wrapper">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<p><a href="/static/slowave/portfolio-post.html" target="_blank"> Exemplo 1 </a></p>
				<p><a href="/static/slowave/portfolio-post2.html" target="_blank"> Exemplo 2 </a></p>
				<p><a href="/static/slowave/portfolio-post3.html" target="_blank"> Exemplo 3 </a></p>
				<p><a href="/static/slowave/portfolio-post4.html" target="_blank"> Exemplo 4 </a></p>
				<p><a href="/static/slowave/portfolio-post5.html" target="_blank"> Exemplo 5 </a></p>
				<p><a href="/static/slowave/portfolio-post6.html" target="_blank"> Exemplo 6 </a></p>
				<p><a href="/static/slowave/portfolio-post7.html" target="_blank"> Exemplo 7 </a></p>
				<p><a href="/static/slowave/portfolio-post8.html" target="_blank"> Exemplo 8 </a></p>
			</div>
		</div>
	</div>
</div>
