<?php $this->layout()->titulo='Palestrante'; ?>
<?php $this->layout()->description='Sobre o palestrante do Workshop de Biomedicina'; ?>
<div class="container-12">
	<div class="grid-12">
		<h1 class="title_h1"> PALESTRANTE</h1>
    <br>
  </div>
  <div class="grid-12">
  <img style="width:30%;float: left;margin-right: 30px;" src="/static/workshopbio/img/draCarol.png"> 
  <h3 style="padding:10px;">Dra. Ana Carolina Puga <br/>Biomédica Esteta</h3>
  <ul style="line-height: 25px;">
    <li>Precursora da Biomedicina Estética no Brasil (Mãe da Biomedicina Estética);</li>
    <li>Presidente-Fundadora da Sociedade Brasileira de Biomedicina Estética-SBBME;</li>
    <li>Presidente do 1º CBBME - Congresso Brasileiro de Biomedicina Estética de 2013 da SBBME;</li>
    <li>Diretora Acadêmica do Núcleo de Estudos e Treinamento Ana Carolina Puga-NEPUGA;</li>
    <li>Diretora da Clínica de Biomedicina Estética ACorPoralle;</li>
    <li>Biomédica Esteta pela Sociedade Brasileira de Biomedicina Estética-SBBME;</li>
    <li>Biomédica Esteta pela Associação Brasileira de Biomedicina-ABBM;</li>
    <li>Coordenadora da 1a Comissão de Biomedicina Estética do CRBM-1 e CFBM;</li>
    <li>Membro da Sociedade Brasileira de Laser em Medicina e Cirurgia-SBLMC;</li>
    <li>Membro da European Medical Laser Association-EMLA;</li>
    <li>Palestrante em diversos congressos e eventos nacionais de Biomedicina Estética e Saúde Estética;</li>
    <li>Ex-Professora da Faculdade de Medicina de Santos;</li>
    <li>Mestra Stricto-Sensu em Ciências da Saúde pela Faculdade de Medicina de Santos;</li>
    <li>Pós-graduada em Hematologia e Hemoterapia pela USP-RP;</li>
    <li>Graduada em Biomedicina pela Barão de Mauá;</li>
</ul>
<div class="box_">
            
            <a href="<?php echo $this->url(array('controller' => 'workshopbio', 'action' => 'inscricoes',), null, true) ?>" title="Inscrições para workshop de Biomedicina Estética">Inscreva-se</a>
        </div>
  </div>
</div>