<section>

    <div class="container">

        <div class="col-sm-12">
            <h1 class="TitulosPaginas">Ajuda Online <small>Baby Cão Clínica Veterinária em Foz do Iguaçu</small></h1>

            <div class="list-group col-sm-3">
                <a href="#" class="list-group-item active">Início</a>
                <a href="exemplo-problema-aberto.html" class="list-group-item">O hospital faz vacinação? Com qual frequência devo vacinar meu cão?</a>
                <a href="exemplo-problema-aberto.html" class="list-group-item">Quais são as especialidades da BabyCão?</a>
                <a href="exemplo-problema-aberto.html" class="list-group-item">Qual é a estrutura da Baby Cão?</a>
                <a href="exemplo-problema-aberto.html" class="list-group-item">Vocês fazem banho e tosa? Vendem produtos de pet shop?</a>
            </div>
            <div class="col-sm-9 TitulosPaginas">
                <div class="alert alert-warning TitulosPaginas" role="alert">
                    <p>Possui alguma dúvida? Aqui procuramos responder as dúvidas mais comuns acerca de nosso hospital e de nossos serviços, caso possua uma dúvida e ela nao esteja respondida aqui, mande-nos uma mensagem.</p>
                </div>
            </div>




        </div>
    </div>

</section>