<h3>Contato Uniamérica.</h3><br>


Você foi aprovado no vestibular 2015/1, porém NÃO conseguiu classificação para BOLSISTA.<br><br>

Caso tenha interesse em ingressar na faculdade, favor procurar a secretaria acadêmica para<br>

realizar sua matrícula no período de 28 de outubro a 29 de novembro de 2014.<br>

Lembramos que temos opções de financiamento através do PRAVALER, onde o aluno paga<br>

50% da mensalidade no dobro de tempo e sem juros. Temos também a opção do FIES<br>

(Financiamento Estudantil) do Governo Federal, onde você pode financiar até 100% de sua<br>

mensalidade.<br><br>

Acesse: http://www.uniamerica.br/contato<br><br>


Data: <?php echo date("d/m/Y") .' - '. date("H:i"); ?>


