<h3>Contato Uniamérica.</h3><br>

Parabéns por sua aprovação no processo seletivo de bolsista 2015/1. <br><br>
Lembramos que as entrevistas para comprovação sócio econômica acontecerão do período 03 a 08 de novembro de 2014,<br>
nossa equipe de atendimento entrará em contato para agendamento de sua entrevista e entrega da documentação.<br><br>

Acesse: http://www.uniamerica.br/contato<br><br>

Data: <?php echo date("d/m/Y") .' - '. date("H:i"); ?>


