<div id="page-content-wrapper">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<form action="" role="form" class="form-horizontal" id="form" method="post" enctype="multipart/form-data">
					<fieldset>

						<legend>SubCategoria Problemas</legend>

						<!-- Select Basic -->
						<div class="form-group">
							<label class="col-md-4 control-label" for="categoria">Categoria &nbsp</label>
							<div class="col-md-4">
								<select id="categoria" name="categoria" class="form-control">

									<?php foreach ($this->atividades as $item): ?>
										<option value="<?php echo $item['idcategoria'] ?>"><?php echo $item['nome'] ?></option>
									<?php endforeach; ?>

								</select>
							</div>
						</div> <br>

						<!-- Text input-->
						<div class="form-group">
							<label class="col-md-4 control-label" for="nome">Nome &nbsp</label>
							<div class="col-md-4">
								<input id="nome" name="nome" type="text" placeholder="" class="form-control input-md">
								<input id="tipo" name="tipo" type="hidden" value="2" class="form-control input-md">
							</div>
						</div><br>

						<!-- Textarea -->
						<div class="form-group">
							<label class="col-md-4 control-label" for="textarea">Descrição &nbsp</label>
							<div class="col-md-4">
								<textarea class="form-control" id="descricao" name="descricao"></textarea>
							</div>
						</div><br>
						<div class="form-group">
							<label class="col-md-4 control-label" for="caminho"></label>
							<div class="col-md-4">
									<button type="submit" id="" name="" class="btn btn-primary">Salvar</button>
							</div>
						</div>

					</fieldset>
				</form>
			</div>

			<div class = "col-lg-12">

				  <?php foreach ($this->atividades as $item): ?>
				  <h2> <?php echo $item['idcategoria'] ?> -  <?php echo $item['nome'] ?> </h2>

				  <table class="table table-hover table-inverse">
				    <thead>
				    <tr>
				      <th>#</th>
				      <th>Nome</th>
				      <th>Descrição</th>
				      <th>Ação</th>
				    </tr>
				    </thead>
				    <tbody>
				    <?php foreach ($this->atividades1 as $item1): ?>
					      <?php if ($item1['categoria_idcategoria'] == $item['idcategoria']){?>
					        <tr>
					          <th scope="row"><?php echo $item['idcategoria'] ?>.<?php echo $item1['idtipo'] ?></th>
					          <td><?php echo $item1['nome'] ?></td>
					          <td><?php echo substr($item1['descricao'], 0, 20); ?>...</td>
					          <td><a href="categoria/excluir/id/<?php echo $item1['idtipo'];?>/tipo/2"><button type="button" class="btn btn-danger">Excluir</button></a></td>
					        </tr>
					      <?php } ?>


				    <?php endforeach; ?>
				  </tbody>
				</table>
				  <?php endforeach; ?>

			</div>
		</div>
	</div>
</div>
