<!-- include summernote -->
<link rel="stylesheet" href="/static/js/summernote-master/dist/summernote-bs4.css">
<script type="text/javascript" src="/static/js/summernote-master/dist/summernote-bs4.js"></script>

<div id="page-content-wrapper">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<form action="" role="form" class="form-horizontal" id="form" method="post" enctype="multipart/form-data">
					<fieldset>

						<legend>SubCategoria Problemas</legend>

						<!-- Select Basic -->
						<div class="form-group">
							<label class="col-md-4 control-label" for="categoria">Categoria &nbsp</label>
							<div class="col-md-4">
								<select id="categoria" name="categoria" class="form-control">

									<?php foreach ($this->atividades as $item): ?>
										<option value="<?php echo $item['idcategoria'] ?>"><?php echo $item['nome'] ?></option>
									<?php endforeach; ?>

								</select>
							</div>
						</div> <br>

						<!-- Text input-->
						<div class="form-group">
							<label class="col-md-4 control-label" for="nome">Nome &nbsp</label>
							<div class="col-md-4">
								<input id="nome" name="nome" type="text" placeholder="" class="form-control input-md">
								<input id="tipo" name="tipo" type="hidden" value="2" class="form-control input-md">
							</div>
						</div><br>

						<!-- Textarea -->
						<div class="form-group">
							<label class="col-md-4 control-label" for="nome">Descricao  &nbsp</label><br>
							<form method="post">
									<textarea id="summernote" name="descricao"></textarea>
							</form>
						</div><br>
						<div class="form-group">
							<label class="col-md-4 control-label" for="caminho"></label>
							<div class="col-md-4">
									<button type="submit" id="" name="" class="btn btn-primary">Salvar</button>
							</div>
						</div>

					</fieldset>
				</form>
			</div>

			<div class = "col-lg-12">

				  <?php foreach ($this->atividades as $item): ?>
				  <h2> <?php echo $item['idcategoria'] ?> -  <?php echo $item['nome'] ?> </h2>

				  <table class="table table-hover table-inverse">
				    <thead>
				    <tr>
				      <th>#</th>
				      <th>Nome</th>
				      <th>Descrição</th>
				      <th>Ação</th>
				    </tr>
				    </thead>
				    <tbody>
				    <?php foreach ($this->atividades1 as $item1): ?>
					      <?php if ($item1['categoria_idcategoria'] == $item['idcategoria']){?>
					        <tr>
					          <th scope="row"><?php echo $item['idcategoria'] ?>.<?php echo $item1['idtipo'] ?></th>
					          <td><?php echo $item1['nome'] ?></td>
					          <td><?php echo $item1['descricao'] ?>...</td>
					          <td><a href="categoria/excluir/id/<?php echo $item1['idtipo'];?>/tipo/2"><button type="button" class="btn btn-danger">Excluir</button></a></td>
					        </tr>
					      <?php } ?>


				    <?php endforeach; ?>
				  </tbody>
				</table>
				  <?php endforeach; ?>

			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
    $(function() {

        $('#summernote').summernote({
            height: 500,
            minHeight: null,
            maxHeight: null,
            focus: true,
            callbacks: {
                onImageUpload: function(files) {
                    editor = $(this);
                    doTheUpload(files[0], editor);
                }
            }
        });

        function doTheUpload(uploadedImage, myEditor) {
            var myForm = new FormData();
            myForm.append("imageField", uploadedImage);
            $.ajax({
                url: "/static/js/summernote-master/editor-upload.php",
                cache: false,
                contentType: false,
                processData: false,
                data: myForm,
                type: "post",
                success: function(imageUrl) {
                    var image = $('<img>').attr('src', imageUrl);
                    $(myEditor).summernote("insertNode", image[0]);
                },
                error: function(myForm) {
                    console.log(myForm);
                }
            });
        }

    });
</script>
