
<section>

    <div class="container">

        <div class="col-sm-12">
            <h1 class="TitulosPaginas">Serviços que oferecemos <small>Baby Cão Clínica Veterinária em Foz do Iguaçu</small></h1>
            <hr>

            <div class="row">

                <div class="col-md-3">
                    <a href="#" class="thumbnail">
                        <img src="http://placehold.it/250x200" alt="petshop">
                    </a>
                </div>

                <div class="col-md-3">
                    <a href="#" class="thumbnail">
                        <img src="http://placehold.it/250x200" alt="petshop">
                    </a>
                </div>

                <div class="col-md-3">
                    <a href="#" class="thumbnail">
                        <img src="http://placehold.it/250x200" alt="petshop">
                    </a>
                </div>

                <div class="col-md-3">
                    <a href="#" class="thumbnail">
                        <img src="http://placehold.it/250x200" alt="petshop">
                    </a>
                </div>

                <div class="col-md-3">
                    <a href="#" class="thumbnail">
                        <img src="http://placehold.it/250x200" alt="petshop">
                    </a>
                </div>

                <div class="col-md-3">
                    <a href="#" class="thumbnail">
                        <img src="http://placehold.it/250x200" alt="petshop">
                    </a>
                </div>

                <div class="col-md-3">
                    <a href="#" class="thumbnail">
                        <img src="http://placehold.it/250x200" alt="petshop">
                    </a>
                </div>

                <div class="col-md-3">
                    <a href="#" class="thumbnail">
                        <img src="http://placehold.it/250x200" alt="petshop">
                    </a>
                </div>



                <nav aria-label="Page navigation center-block">
                    <ul class="pagination">
                        <li>
                            <a href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <li><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li>
                            <a href="#" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>






        </div>
    </div>

</section>