<div class="container-12">
    <div class="grid-12">
        <h2> EIXO 1</h2>
        
         <p><strong>
                A ATUAÇÃO DO BANCO MUNDIAL NO CAMPO POLÍTICO – ECONÔMICO ARTICULADA À EDUCAÇÃO BRASILEIRA: UMA APROXIMAÇÃO
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO1/Eixo1_A atuação do Banco mundial no campo político econômico aticulada à educação brasileira uma aproximação.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
         <p><strong>
                AS POLÍTICAS DE AVALIAÇÃO NOS ANOS INICIAS DO ENSINO FUNDAMENTAL: PROVA BRASIL
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO1/Eixo1_As politicas de avaliaçao nos anos iniciais do ensino fundamental.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
         <p><strong>
                AVALIAÇÃO INSTITUCIONAL, CONTEÚDO E PROCESSO ESTRATÉGICO EM ESCOLAS TÉCNICAS DO ESTADO DO PARANÁ 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO1/Eixo1_Avaliaçao institucional, conteúdo e processo estratégico em escolas tecnicas do estado do PR.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
         <p><strong>
                COMPROMISSO SOCIAL DAS IES E AVALIAÇÃO INSTITUCIONAL – UMA ANÁLISE SOBRE O SINAES/BRASIL 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO1/Eixo1_Compromisso Social das IES e Avaliação Institucional – uma análise sobre o SINAES Brasil.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
         <p><strong>
                ENSINO FUNDAMENTAL DE NOVE ANOS, AVANÇOS E RETROCESSOS NAPOLÍTICA EDUCACIONAL DE AVALIAÇÃO EM LARGA ESCALA NA REDE DE ENSINO DE FOZ DO IGUAÇU/PR¹
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO1/Eixo1_Ensino fundamental de nove anos,avanços e e retrocessos na polica eucacional de avaliação em larga escal.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
         <p><strong>
                IMPACTOS DO PROGRAMA BOLSA FAMÍLIA NO RENDIMENTO ESCOLAR: APONTAMENTOS CONCEITUAIS E IMPRESA. 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO1/Eixo1_Impactos do programa bolsa familia no rendimento escolar apontamentos conceituais e imprensa.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                MAPEAMENTO DOS SISTEMAS ESTADUAIS DE AVALIAÇÃO EM LARGA ESCALA DA EDUCAÇÃO 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO1/Eixo1_Mapeamento dos sistemas estaduais de avaliação em larga escala da educação.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                O REGIME MILITAR E A REFORMA UNIVERSITÁRIA DE 1968: O CAMINHO PARA AS AVALIAÇÕES NA EDUCAÇÃO SUPERIOR 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO1/Eixo1_O regime militar e a reforma univeritária de 1968.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                A PRODUÇÃO DE TEXTOS NA PROVA BRASIL E NO LIVRO DIDÁTICO ADOTADO NO MUNICÍPIO DE FOZ DO IGUAÇU¹
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO1/Eixo1_Producao de textos na prova Brasil e no livro didático adotado em Foz do iguaçu.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                UMA ANÁLISE SOBRE AS REFORMAS NA EDUCAÇÃO SUPERIOR BRASILEIRA DO REGIME MILITAR AO GOVERNO FHC 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO1/Eixo1_Uma analise sobre as reformas na educaçao superior brasileirado regime militar ao governo FHC.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        
    </div>
     <div class="grid-12">
        <h2> EIXO 2</h2>
        
         <p><strong>
                A CONSTRUÇÃO DO CURSO LICENCIATURA EM EDUCAÇÃO DO CAMPO NA UNIOESTE
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO2/Eixo2_A construção do curso de licenciatura em educação do campo na unioeste.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
         <p><strong>
                A RELEVÂNCIA DA FAMÍLIA NO DESENVOLVIMENTO DA PESSOA COM DEFICIÊNCIA INTELECTUAL 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO2/Eixo2_A relevância da família no desenvolvimento da pessoa com deficiência intelectual.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
         <p><strong>
                AS PRÁTICAS EDUCATIVAS PARA CRIANÇAS COM SINDROME DE DOWN EM ESCOLAS REGULARES 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO2/Eixo2_As práticas educativas para crianças com Sindrome de Down em escolas regulares.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
         <p><strong>
                EDUCAÇÃO DE JOVENS E ADULTOS (EJA): UM ESTUDO DE CASO 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO2/Eixo2_Educação de jovens e adultos_um estudo de caso.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
         <p><strong>
                O ESTADO E A EDUCAÇÃO DE JOVENS E ADULTOS: UMA REFLEXÃO SOBRE A OFERTA DE ESCOLARIZAÇÃO PARA ESTÁ MODALIDADE DE ENSINO. 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO2/Eixo2_O estado e a educaçao de jovens e adultos.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
          <p><strong>
                O HISTÓRICO DA IMPLEMENTAÇÃO DA EDUCAÇÃO A DISTÂNCIA NO PARQUE TECNOLÓGICO ITAIPU 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO2/Eixo2_O histórioc da implementaçao da EAD no PTI.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
          <p><strong>
                O PROGRAMA PAENE E A INCLUSÃO DAS PESSOAS COM DEFICIÊNCIA NA EDUCAÇÃO SUPERIOR 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO2/Eixo2_O Programa Paene e a inclusão das pessoas com deficiência na Educação Superior.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
          <p><strong>
                PESSOA COM ALTAS HABILIDADES/SUPERDOTAÇÃO: PRODUTO GENÉTICO? PRODUTO AMBIENTAL?
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO2/Eixo2_Pessoa com altas habilidades superdotação_produto genetico_produto ambiental.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
     </div>
      <div class="grid-12">
        <h2> EIXO 3</h2>
        
         <p><strong>
                A ALDEIA AVÁ – GUARANI EM SÃO MIGUEL DO IGUAÇU E A AVALIAÇÃO DOSALUNOS NAS ESCOLAS REGULARES 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO3/Eixo3_A aldeia avá – guarani em são miguel do iguaçu e a avaliação dos alunos nas escolas regulares.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                A ESCOLARIZAÇÃO SOB A LUZ DAS TEORIAS FREUDIANAS 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO3/Eixo3_A escolarização sob a luz das teorias freudianas.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                A LITERATURA E SUA TRAJETÓRIA NO PROCESSO DE CONSTRUÇÃO DA APRENDIZAGEM 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO3/Eixo3_A literatura e sua trajetória no processo de construção da aprendizagem.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                ALFABETIZAÇÃO PARA ALÉM DOS METODOS TRADICIONAIS DE ENSINO 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO3/Eixo3_Alfabetiozação para além dos métodos tradicionais de ensino.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                ALFABETIZAR NA EDUCAÇÃO INFANTIL: LIMITES E POSSIBILIDADES 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO3/Eixo3_Alfabetização na educação infantil limites e possibilidades.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                ALFABETIZAR NA EDUCAÇÃO INFANTIL 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO3/Eixo3_Alfabetizar na educacao infantil.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                AS CONTRIBUIÇÕES DA LITERATURA INFANTIL PARA A FORMAÇÃO DA CRIANÇA LEITORA 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO3/Eixo3_As contribuiçoes da educaçao infantil para a formaçao da criança leitora.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                 EDUCAÇÃO AMBIENTAL POR MEIO DO LÚDICO PARA O PÚBLICO INFANTIL
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO3/Eixo3_Educação ambiental por meio do lúdico para o público infantil.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                O DESENHO INFANTIL NA PERSPECTIVA HISTÓRICO CULTURAL
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO3/Eixo3_O desenho na perspectiva hitorico cultural.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                O PROCESSO DE DIALETAÇÃO DA LÍNGUA PORTUGUESA EM MOÇAMBIQUE E OS DESAFIOS PARA O ENSINO E APRENDIZAGEM: PROBLEMAS E PERSPECTIVAS. 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO3/Eixo3_O processo de dialetação da língua portuguesa em moçambique e os desafios para o ensino e aprendizagem.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                OS JOGOS PEDAGÓGICOS: CONTRIBUIÇÕES ACERCA DO DESENVOLVIMENTO COGNITIVO A PARTIR DAS ATIVIDADES ESCOLARES.
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO3/Eixo3_Os jogos pedagógicos contribuições acerca do desenvolvimento cognitivo a partir das atividades escolares.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                PESQUISA SOBRE OS USOS DO LIVRO DIDÁTICO NO ENSINO DA LEITURA E DA ESCRITA: IMPORTÂNCIA E POSSIBILIDADES 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO3/Eixo3_Pesquisa sobre os usos do livro didático no ensino da leitura e da escrita - importancia e possibilidade.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                POSSIBILIDADES DO LETRAMENTO NA INFÂNCIA: A FORMAÇÃO DO CIDADÃO CRÍTICO E AUTÔNOMO. 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO3/Eixo3_Possibilidades do letramento na infancia.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                TRANSTORNO DE DÉFICIT DE ATENÇÃO E HIPERATIVIDADE EM CRIANÇAS: O TRATAMENTO COM METILFENIDATO 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO3/Eixo3_Transtorno de deficit de atencao e hiperatividade em crianças o tratamento com metilfenidato.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                UM OLHAR SOBRE O ENSINO BILÍNGUE: PROJETO ESCOLAS BILÍNGUES DE FRONTEIRA, FOZ DO IGUAÇU – PUERTO IGUAZU 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO3/Eixo3_Um olhar sobre o ensino bilíngue - projetos escolas bilingues de fronteiras.pdf" target="blank_"> Baixar PDF </a>
        </p>
      </div>
    <div class="grid-12">
        <h2> EIXO 4</h2>
        
         <p><strong>
                A INTERNET COMO PROPOSTA DE ESTUDO DOS CONTEÚDOS DE GEOGRAFIA NO ENSINO FUNDAMENTAL
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO4/Eixo4_A internet como proposta de estudo dos conteudos de geografia no ensino fundamental.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
               A PERCEPÇÃO E O USO DOS RECURSOS TECNOLÓGICOS NO CONTEXTO DA EDUCAÇÃO
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO4/Eixo4_A percepção e o uso dos recursos tecnológicos no contexto da educaçao.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                BREVE HISTÓRIA DA TRÍPLICE FRONTEIRA: EXTENSÃO, DOCÊNCIA E TECNOLOGIAS
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO4/Eixo4_Breve historia da triplice fronteira.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                CIDADANIA E HUMANIZAÇÃO NO DESENVOLVIMENTO DA CRIANÇA E ADOLESCENTE NA VIDA SOCIAL E FAMILIAR. 

            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO4/Eixo4_Cidadania e humanizacao no desenvolvimento da criança e adolescente na vida social e familiar.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                JOGOS PEDAGÓGICOS – LÚDICOS NA EUCAÇÃO NÃO FORMAL 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO4/Eixo4_Jogos pedagogicos-ludicos na educaçao não formal.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                POR QUE REALIZAR PROJETOS DE INICIAÇÃO CIENTÍFICA COM CRIANÇAS E ADOLESCENTES EM SITUAÇÃO DE RISCO? 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO4/Eixo4_Por que realizar projetos de iniciação científica com rianças e adolescente em situaçao de risco.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                PROCESSO DE INDUÇÃO E FUNÇÃO DO PRIMEIRO GRAU COM USO DE EXPERIMENTO MATEMÁTICO¹
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO4/Eixo4_Processo de indução e função do primeiro grau  com uso de experimento matemático.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                “TÁ CHOVENDO HAMBÚRGUER”: UMA EXPERIÊNCIA DE LEITURA PEDAGÓGICA¹
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO4/Eixo4_Tá chovendo hamburguer - uma experiencia de leitura pedagogica.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        </div>
    <div class="grid-12">
        <h2> EIXO 5</h2>
        <p><strong>
                A CRIANÇA E SUAS APRENDIZAGENS EM HISTÓRIA NA SEGUNDA DÉCADA DO SÉCULO XXI
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO5/Eixo5_A_criança_e_suas_aprendizagens_em_Historia_na_segunda_decada_do_seculo_XXI.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                AVALIAÇÃO NA EDUCAÇÃO INFANTIL: QUAIS OS CRITÉRIOS AVALIATIVOS? QUE PROFESSORES? QUE FORMAÇÃO?
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO5/Eixo5_Avaliação na educaçao infantil_quais os criterios avaliativos_que professores_que formacao.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                CORRENTES EPISTEMOLÓGICAS NA PRODUÇÃO DO CONHECIMENTO EM EDUCAÇÃO: BREVES CONSIDERAÇÕES1
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO5/Eixo5_Correntes epistemológicas na produção do conhecimento em educação breves considerações.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                O ESPÍRITO CIENTÍFICO E A CONSTRUÇÃO DE APRENDIZAGENS COM CRIANÇAS DOS ANOS INICIAIS DO ENSINO FUNDAMENTAL 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO5/Eixo5_O espírito científico e a construção de aprendizagens com crianças dos anos iniciais do ensino fundament.pdf" target="blank_"> Baixar PDF </a>
        </p>
    </div>
    
     <div class="grid-12">
        <h2> EIXO 6</h2>
         <p><strong>
                A DESBUROCRATIZAÇÃO DO PEDAGOGO NA ESCOLA PÚBLICA: UM ESTUDO DE CASO NUM COLÉGIO ESTADUAL DE SANTA TEREZINHA DE ITAIPU.
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO6/Eixo6_A desburocratização do Pedagogo na Escola Pública.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                A FUNÇÃO DOCENTE NA EDUCAÇÃO INFANTIL: UM ESTUDO DE CASO EM UM CENTRO MUNICIPAL DE EDUCAÇÃO INFANTIL DO EXTREMO OESTE DO PARANÁ
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO6/Eixo6_A função docente na educaçao infantil.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                AS POSSIBILIDADES DE FORMAÇÃO DOS PROFESSORES DA REDE MUNICIPAL A PARTIR DO PROJETO LABORATÓRIO VIVO DE CIÊNCIAS NATURAIS E CUIDADO COM O MEIO AMBIENTE
            </strong>
                <br/>
        <a href="/static/congresso/anais/EIXO6/Eixo6_As possibilidades de formaçao dos professores da rede municipal a partir do projeto  Laboratório vivo de.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                AVALIAÇÃO DO CONSUMO DE FRUTAS E VERDURAS EM ADOLESCENTES DE UMA ESCOLA PÚBLICA 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO6/Eixo6_Avaliaçao do consumo de frutas e verduras em adolescetes de uma escola publica.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
               DESENVOLVIMENTO DE EQUIPES DE EXCELÊNCIA E A CONTRIBUIÇÃO DESTA NO SUCESSO DE ORGANIZAÇÕES ESCOLARES 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO6/Eixo6_Desenvolvimento de equipes de excelência.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                DISTÚRBIOS DE APRENDIZAGEM E O PROCESSO EDUCATIVO 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO6/Eixo6_Disturbios de aprendizagens e o processo educativo.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                LACUNAS E AUSÊNCIAS NOS CURRÍCULOS DOS CURSOS DE PEDAGOGIA NO QUE DIZ RESPEITO ÀS TECNOLOGIAS DA INFORMAÇÃO E COMUNICAÇÃO (TICS) E CÊNCIAS COGNITIVAS 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO6/Eixo6_Lacunas e ausências nos currículos dos Cursos de Pedagogia no que diz respeito Às TICs e Ciêncxias Cogni.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
        <p><strong>
                MOTIVAÇÃO INICIAL NA FORMAÇÃO DE LICENCIANDOS 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO6/Eixo6_Motivaçao inicial na formaçao de licenciados.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
         <p><strong>
                O ESTÁGIO SUPERVISIONADO EM HISTÓRIA: LIMITES E POSSIBILIDADES NA ATUAÇÃO DOCENTE DO ACADEMICO DE HISTÓRIA. 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO6/Eixo6_O estagio supervisionado em história limites e possibilidades na atuação docente do academico de históri.pdf" target="blank_"> Baixar PDF </a>
        </p>
        
         <p><strong>REFLEXÕES EM TORNO DA SOCIALIZAÇÃO PROFISSIONAL NA FORMAÇÃO INICIAL DE PROFESSORES: MAL-ESTAR E BEM-ESTAR DOCENTE 
            </strong>
            <br/>
        <a href="/static/congresso/anais/EIXO6/Eixo6_Reflexoes em torno da socializaçao profissional na formacao inicial de professores mal-estar e bem-estar.pdf" target="blank_"> Baixar PDF </a>
        </p>
        </div>
</div>