<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>IV Congresso Internacional de Educação e VII Semana Acadêmica de Pedagogia</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">
        <link rel="stylesheet" href="/static/congresso/css/estilos.css">
        <link rel="stylesheet" href="/static/congresso/css/style.css">
        <link rel="stylesheet" href="/static/congresso/css/slider.css">

        <!-- html5.js for IE less than 9 -->
        <!--[if lt IE 9]>
            <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <!-- css3-mediaqueries.js for IE less than 9 -->
        <!--[if lt IE 9]>
            <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
        <![endif]-->

        <script src="/global/jquery-validation/lib/jquery.js"></script>
        <script src="/global/jquery-validation/dist/jquery.validate.min.js"></script>
        <script src="/global/jquery-validation/localization/messages_pt_BR.js"></script>
        <script src="/global/jquery-validation/dist/additional-methods.js"></script>
        <script src="/global/jquery.maskedinput.min.js"></script>
        <script src="/global/global.js"></script>
        <script type="text/javascript">
            jQuery(function($) {
                $('#nascimentodata').mask('99/99/9999');
            });
        </script>
    </head>
    <body>
        <div class="geral">
            <header>
                <div id="header">
                    <h1>
                        <a title="IV CONGRESSO INTERNACIONAL DE EDUCAÇÃO" href="<?php echo $this->url(array('controller' => 'congresso', 'action' => 'index',), null, true) ?>">
                            <img alt="LOGO IV CONGRESSO INTERNACIONAL DE EDUCAÇÃO" class="logo" width="300" height="149" src="/static/congresso/img/logo.png" />
                        </a>
                    </h1>
                    <menu id="top">
                        <ul>
                            <li><strong><a href="<?php echo $this->url(array('controller' => 'congresso', 'action' => 'index',), null, true) ?>">Home</a></strong></li>
                            <li><strong><a href="<?php echo $this->url(array('controller' => 'congresso', 'action' => 'congresso',), null, true) ?>">O Congresso</a></strong></li>
                            <li><strong><a href="<?php echo $this->url(array('controller' => 'congresso', 'action' => 'programacao',), null, true) ?>">Programação</a></strong></li>
                            <li><strong><a href="<?php echo $this->url(array('controller' => 'congresso', 'action' => 'palestrantes',), null, true) ?>">Palestrantes</a></strong></li>
                            <li><strong><a href="<?php echo $this->url(array('controller' => 'congresso', 'action' => 'normas',), null, true) ?>">Normas</a></strong></li>
                            <li><strong><a href="<?php echo $this->url(array('controller' => 'congresso', 'action' => 'inscricoes',), null, true) ?>">Inscrições</a></strong></li>
                            <li><strong><a href="<?php echo $this->url(array('controller' => 'congresso', 'action' => 'contato',), null, true) ?>">Contato</a></strong></li>
                        </ul>
                    </menu>
                </div>
                <div class="linha"></div>
            </header>
            <article>
                <?php echo $this->layout()->content; ?>
            </article>
        </div>
        <footer>
            <div class="alinha">
                <div class="left">
                    <font>Realização:</font>
                    <a href="http://www.uniamerica.br/" target="blank_"><img class="realizacao" src="/static/congresso/img/uniamerica.png"></a>
                </div>
                <div class="right">
                    <font>Apoio:</font>
                    <a href="http://www.hoper.com.br/" target="blank_">
                        <img src="/static/congresso/img/hoper.png">
                    </a>
                    <a href="http://www.eficazfoz.com.br/" target="blank_">
                        <img src="/static/congresso/img/eficaz.png">
                    </a>
                    <a href="#">
                        <img src="/static/congresso/img/pasini.jpg">
                    </a>
                    <a href="#">
                        <img src="/static/congresso/img/multivinculos.png">
                    </a>
                    <a href="http://www.rafainpalace.com.br/v2/home/" target="blank_">
                        <img src="/static/congresso/img/rafain.png">
                    </a>
                     <a href="http://www.pti.org.br/" target="blank_">
                        <img src="/static/congresso/img/pti.png">
                    </a>
                     <a href="http://www.hotelcoroadosfoz.com.br/nova/" target="blank_">
                        <img src="/static/congresso/img/coroados.png">
                    </a>
                </div>
            </div>
            <div class="copyright">
                <p>© UNIAMÉRICA 2013. Todos os direitos reservados.</p>
            </div>
        </footer>
    </body>
</html>