<div class="container-12">
	<div class="grid-12">
		<h1> PROGRAMAÇÃO </h1>
	</div>
  <div class="grid-12 list">
    <h3>17 de outubro (quinta-feira)</h3>
    <hr>
    <div class="grid-4">08h00 às 09h00 </div>
    <div class="grid-8">Credenciamento e Welcome coffee.</div>

    <div class="grid-4">09h00 às 11h00 </div>
    <div class="grid-8">Palestra: "O processo da dialetação da língua portuguesa em Moçambique e os desafios para o ensino e aprendizagem: problemas e perspectivas."
      <br>Palestrante: Ilídio Macaringue (Moçambique)
      <br>Mediação: Prof. Mestrando Armando Daros Junior
    </div>

    <div  class="grid-4">18h30 às 19h30 </div>
    <div  class="grid-8">Credenciamento e Welcome coffee.</div>

    <div  class="grid-4">19h30 às 20h30  </div>
    <div class="grid-8"> Palestra: "Qualidade e inovação na educação"
      <br> Palestrante: Prof. Pós-doutor Pedro Demo.</div>

      <div  class="grid-4">20h30 às 21h30 </div>
      <div class="grid-8">Palestra: "Políticas de avaliação e a questão da Inovação Educacional: avanços ou retrocesso?"
        <br>Palestrante: Prof. Dr. Valdecir Soligo
        <br>Mediação: Profª. Doutoranda Juliana Serraglio Pasini.
      </div>
      <div  class="grid-4">21h30 </div>
      <div class="grid-8">Debate.</div>
    </div>
    <div class="grid-12 list">
      <h3>18 de outubro (sexta-feira)</h3>
      <hr>
      <div class="grid-4">08h00 às 09h00</div>
      <div class="grid-8">Palestra: "As mídias digitais na educação."
        <br>Palestrante: Ryon Braga
        <br>Mediação:  Profª. Mestranda Ivanir Gomes da Silva
        e Profª. Mestre Jamily Charão Vargas. </div>

        <div class="grid-4">09h30 às 11h00 – Mini-Cursos</div>
        <div class="grid-8">
          <span> &rarr; Os limites educativos (Especialista Rosiane Delgado/Multivínculos)</span>
          <span> &rarr; Encantar as crianças a partir das ciências naturais (Prof.ª Mestre Fatima Regina Debald).</span>
          <span> &rarr; Ensino e Tecnologia: ferramentas on-line e gratuitas para suas aulas (Prof. Mestre Micael Alvino e Prof. Doutorando Blasius Debald).</span>
          <span> &rarr; A arte oratória e contribuições na produção textual (Prof.ª Mestre Carmen Aparecida Nunes).</span>
          <span> &rarr; Brincando com papel e dobraduras (Prof.ª Mestranda Jane Glauce).</span>
          <span> &rarr; Autonomia na educação (Prof.ª Mestre Nazaré de Oliveira Almeida).</span>
          <span> &rarr; Gênero e Educação (Prof. Mestre Carlos Berguer).</span>
          <span> &rarr; A utilização do cinema no ensino da geografia (Prof.ª Doutoranda Claudia Heloisa Conte).</span>
          <span> &rarr; Neurociências: o jogo no ambiente escolar (Equipe Pedagógica do Instituto Eficaz Foz).</span>
          <span> &rarr; Acidentes mais comuns na infância - Luciana Winter.</span>
        </div>
        
        <div class="grid-4">19h30 às 20h30 </div>
        <div class="grid-8">Palestra: "Era digital, culturas juvenis e escola: formação de professores para um mundo em mudança."
          <br>Palestrante: Prof. Pós-Doutor José Carlos Libâneo 
          <br>Mediação: Prof. Pós-Doutor João Jorge Correa e Profª. Mestranda Thuinie Medeiros Vilela Daros.
        </div>
        <div  class="grid-4">20h30 </div>
        <div class="grid-8">Debate.</div>
      </div>
      <div class="grid-12 list">
        <h3>19 de outubro (sábado)</h3>
        <hr>
        <div class="grid-4">08h00 às 12h00</div>
        <div class="grid-8">Apresentação de trabalhos.</div>
      </div>
      
    </div>