
<section>

    <div class="container">

        <div class="col-sm-12">
            <h1 class="TitulosPaginas">Serviços que oferecemos <small>Baby Cão Clínica Veterinária em Foz do Iguaçu</small></h1>


            <div class="alert alert-warning TitulosPaginas" role="alert">
                <p>
                    Em nossa Clínica procuramos garantir que seu animal de estimação receberá um tratamento completo e com qualidade, para isso, além de contarmos com grandes profisionais, procuramos oferecer serviços que abrangem todas as áreas do tratamento animal.
                </p>
            </div>

            <ul class="list-unstyled list-inline TitulosPaginas">
                <li class="col-sm-6 MinServicos">
                    <Img src="http://placehold.it/530x250" class="img-rounded">
                    <h3>Castração</h3>
                    <p>
                        Outono é a época mais adequada para esterilização (castração) de cães e gatos.
                        A castração de machos e fêmeas apresenta várias vantagens, iniciando pelo maior índice de longevidade em comparação aos não castrados.
                        Menor incidências de traumas provocados por brigas, e até graves traumas ocasionado por atropelamentos e outras ocorrências.
                        Cães e gatos castrados são mais companheiros e fazem melhor interação com crianças dos que os não castrados.
                        Venha! Participe da nossa campanha!
                    </p>
                </li>
                <li class="col-sm-6 MinServicos">
                    <Img src="http://placehold.it/530x250" class="img-rounded">
                    <h3>Atendimento de emergência</h3>
                    <p>
                        O atendimento de emergência funciona 24h por dia. E em nossa estrutura contamos com um grande diferencial em relação a outras clínicas: aqui o seu animal de estimação não será atendido apenas por um veterinário de plantão, mas, se for necessário, também por uma equipe de especialistas pronta para realizar atendimentos, exames e procedimentos cirúrgicos. Outro diferencial nosso é a priorização pela cirurgia imediata ao invés da internação e postergação do tratamento.
                    </p>
                </li>
                <li class="col-sm-6 MinServicos">
                    <Img src = "http://placehold.it/530x250" class="img-rounded">
                    <h3>Check-up</h3>
                    <p>
                        Na Baby Cão seu animal de estimação pode fazer um check-up para verificar como está a saúde dele. Nesse processo também é feito a vermifugação e exames bioquímicos, tudo para prevenir problemas maiores no futuro.
                    </p>
                </li>
                <li class="col-sm-6 pull-left MinServicos" >
                    <Img src = "http://placehold.it/530x250" class="img-rounded">
                    <h3>Vacinação</h3>
                    <p>
                        Possuímos todas as vacinas já disponíveis em nossa estrutura, armazenadas nas temperaturas adequadas. Realizamos a vacinação dos animais seguindo a tendência internacional de maior espaçamento de tempo entre as aplicações, evitando o excesso de vacinação que pode fragilizar a saúde do animal em vez de prevenir doenças. Fazemos a imunização de cães e gatos, adultos e filhotes.
                    </p>
                </li>
                <li class="col-sm-6 MinServicos">
                    <Img src = "http://placehold.it/530x250" class="img-rounded">
                    <h3>Tratamento de câncer</h3>
                    <p>
                        A Baby Cão é um centro de referência em diagnóstico e tratamento de câncer em Foz do Iguaçu, curando ou prolongado a vida de animais em até dois anos. Tudo é feito com antibióticos com poderes quimioterápicos, preparados em um centro de oncologia humana em dosagens apropriadas para os animais, proporcionando um tratamento de baixa agressividade.

                    </p>
                </li>
                <li class="col-sm-6 MinServicos">
                    <Img src = "http://placehold.it/530x250" class="img-rounded">
                    <h3>Internamento</h3>
                    <p>
                        Nos casos de emergência, os animais podem ser internados no hospital pelo tempo necessário à recuperação das cirurgias e procedimentos que precisem de cuidados intensivos.
                    </p>
                </li>
                <li class="col-sm-6 MinServicos">
                    <Img src = "http://placehold.it/530x250" class="img-rounded">
                    <h3>Radiologia</h3>
                    <p>
                        O exame radiológico, popularmente chamado de “Raio X”, é um procedimento bastante utilizado, justamente por permitir a detecção de uma série de problemas. Entre eles podemos citar: fraturas, doenças ósseas, enfermidades internas de tórax e abdômen, como deformidades cardíacas e tumores. Além disso, possibilita a contagem de filhotes ainda no abdômen do animal.
                    </p>
                </li>
                <li class="col-sm-6 MinServicos">
                    <Img src = "http://placehold.it/530x250" class="img-rounded">
                    <h3>Eletrocardiograma</h3>
                    <p>
                        Esse procedimento não invasivo é realizado sem anestesia, com eletrodos presos à pele do tórax do animal. Ele é indicado para a detecção precisa de arritmia cardíaca, fibrilações brandas, entre e outros problemas cardíacos. Também é importante antes de cirurgias.
                    </p>
                </li>
                <li class="col-sm-6 MinServicos">
                    <Img src = "http://placehold.it/530x250" class="img-rounded">
                    <h3>Ultrassonografia</h3>
                    <p>
                        Trata-se de uma técnica diagnóstica por imagem, não invasiva, que utiliza o ultrassom para a detecção de problemas e alterações internas, nos órgãos dos animais. É muito utilizado em complemento à radiologia para a obtenção de um diagnóstico preciso.
                    </p>
                </li>
                <li class="col-sm-6 MinServicos">
                    <Img src = "http://placehold.it/530x250" class="img-rounded">
                    <h3>Ecocardiografia</h3>
                    <p>
                        O ecocardiograma é, em termos mais simples, uma “ultrassonografia do coração”. Trata-se de uma técnica não invasiva utilizada para avaliar o coração dos animais em tempo real, fornecendo um diagnóstico mais completo em casos de distúrbios de válvulas, cardiopatia, cardiomegalia, doenças congênitas, entre outros.
                    </p>
                </li>
                <li class="col-sm-6 MinServicos">
                    <Img src = "http://placehold.it/530x250" class="img-rounded">
                    <h3>Rinoscopia</h3>
                    <p>
                        A Rinoscopia é um exame que fornece uma imagem exata do interior da cavidade nasal do animal, e permite a coleta de amostras e identificação de corpos estranhos. Ele é feito com anestesia e pode identificar casos de rinite, tumores, pólipos, ou até galhos de plantas que ficam presos na cavidade nasal. A Baby Cão é uma das poucas clínicas que oferece esse serviço em Foz do Iguaçu.
                    </p>
                </li>
                <li class="col-sm-6 MinServicos">
                    <Img src = "http://placehold.it/530x250" class="img-rounded">
                    <h3>Eletrorretinografia</h3>
                    <p>
                        Trata-se de um exame não invasivo, sem necessidade de anestesia, feito com um equipamento exclusivo que o HVSB possui, tendo como finalidade avaliar o funcionamento da retina do animal. A Eletrorretinografia é importante no pré-operatório de cirurgias de catarata, no diagnóstico precoce de doenças como a Degeneração Retiniana Hereditária e a Sudden Adquired Retinal Degeneration; e, de maneira geral, é determinante para cirurgias e tratamentos de vista, pois não são incomuns os casos em que o animal aparenta enxergar, mas está cego.
                    </p>
                </li>
                <li class="col-sm-6 MinServicos">
                    <Img src = "http://placehold.it/530x250" class="img-rounded">
                    <h3>Fisioterapia</h3>
                    <p>
                        A Babycão conta com uma parceria com um profissional de fisioterapia que faz diversos tipos de técnicas terapêuticas com os animais na estrutura do hospital e, dependendo da terapia, em locais externos.

                    </p>
                </li>
                <li class="col-sm-6 MinServicos">
                    <Img src = "http://placehold.it/530x250" class="img-rounded">
                    <h3>Broncoscopia</h3>
                    <p>
                        A Broncoscopia é um exame que permite a investigação e coleta de amostras dos pulmões. Para isso o animal é sedado e então se utiliza um tubo flexível ou rígido apropriado para a avaliação da traqueia e brônquios. Esse procedimento é indicado para o diagnóstico em casos de tosses crônicas, corpos estranhos, infiltrações pulmonares, entre outros.
                    </p>
                </li>
                <li class="col-sm-6 MinServicos">
                    <Img src="http://placehold.it/530x250" class="img-rounded">
                    <h3>Colonoscopia</h3>
                    <p>
                        Muito utilizado no diagnóstico de casos de diarreia crônica e sangue nas fezes, a colonoscopia é um procedimento feito com um endoscópio introduzido pelo ânus do animal sob anestesia. Com ele é possível detectar casos como colite, úlceras, parasitas, além de câncer de colo retal.
                    </p>
                </li>
                <li class="col-sm-6 MinServicos">
                    <Img src="http://placehold.it/530x250" class="img-rounded">
                    <h3>Banho e tosa</h3>
                    <p>
                        Com uma empresa terceirizada operando dentro da estrutura da Baby Cão, oferecendo serviços de pet shop e banho e tosa para cães e gatos.
                    </p>
                </li>

            </ul>
        </div>
    </div>

</section>