<div id="page-content-wrapper">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<form action="" role="form" class="form-horizontal" id="form" method="post" enctype="multipart/form-data">
					<fieldset>

						<legend>Menu - Categoria</legend>

						<!-- Text input-->
						<div class="form-group">
							<label class="col-md-4 control-label" for="nome">Nome  &nbsp</label>
							<div class="col-md-4">
								<input id="nome" name="nome" type="text" placeholder="" class="form-control input-md">
								<input id="tipo" name="tipo" type="hidden" value="1" class="form-control input-md">
							</div><br>
							<label class="col-md-4 control-label" for="nome">Descricao  &nbsp</label><br>
							<div class="grid-container">
								<div class="grid-width-100">
									<textarea name="descricao" id="editor">&lt;p&gt;Initial editor content.&lt;/p&gt;</textarea>
								</div>
							</div>
						</div>
						<br>
						<div class="form-group">
							<label class="col-md-4 control-label" for="caminho"></label>
							<div class="col-md-4">
								<button type="submit" id="" name="" class="btn btn-primary">Salvar</button>
							</div>
						</div>
					</fieldset>
				</form>

			</div>

			<div class = "col-lg-12">
				<table class="table table-hover table-inverse">
					<thead>
					<tr>
						<th>#</th>
						<th>Nome</th>
						<th>Descrição</th>
						<th>Ação</th>
					</tr>
					</thead>
					<tbody>
							<?php foreach ($this->atividades as $item): ?>
								<tr>
									<th scope="row"><?php echo $item['idcategoria'] ?></th>
									<td><?php echo $item['nome'] ?></td>
									<td><?php echo $item['descricao'] ?></td>
									<td><a href="categoria/excluir/id/<?php echo $item['idcategoria'];?>"><button type="button" class="btn btn-danger" onclick="return confirm('Deletando a categoria as subcategorias serão todas deletadas');"">Excluir</button></a></td>
								</tr>
							<?php endforeach; ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
