<div class="container-12">
	<div class="grid-12">
		<h1>DESAFIANDO AS FRONTEIRAS DO CONHECIMENTO</h1>
		<font  class="text-congresso" size="3" style="text-align:justify">
			O IV Congresso Internacional de Educação e a VII Semana Acadêmica de Pedagogia da Uniamérica abrem espaço para discutir os desafios impostos aos profissionais de Educação.  Os rumos da profissionalização do docente, a inovação e as pesquisas em diversas áreas da educação serão os assuntos em pauta. 
			Voltado para professores, pesquisadores e acadêmicos, o evento contará com convidados de renome nacional e internacional, sendo dividido em palestras, minicursos e espaço para apresentação de trabalhos. 
		</font>
	</div>
</div>