<h3>Contato Uniamérica.</h3>
<pre>
Olá {nome_de}

Você está recebendo este e-mail porque a Uniamérica exige que todos os e-mails enviados através do website sejam confirmados por seus remetentes. Utilize o link abaixo para confirmar o envio de sua mensagem.

<a href="http://www.uniamerica.com.br/congresso/contato/confirmar/chave/{chave}">http://www.uniamerica.com.br/congresso/contato/confirmar</a>

Caso seu gerenciador de e-mails bloqueie o link em mensagens HTML, copie o endereço abaixo e cole no campo destino ao endereço de páginas:

http://www.uniamerica.com.br/congresso/contato/confirmar/chave/{chave}

Um forte abraço!

Equipe Uniamérica.

IP: <?php echo getenv("REMOTE_ADDR"); ?>

Data: <?php echo date("d/m/Y") .' - '. date("H:i"); ?>
</pre>