<div class="container-12">
    <div class="grid-12">
        <div class="sucesso">
            <h3>Sua mensagem foi enviada com sucesso.</h3>
        </div>
    </div>
    <div class="grid-12">
        <h2 class="sublinhado inline-block-list float-right">Nossa Localização</h2>
        <iframe frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.br/maps?q=uniam%C3%A9rica+foz&amp;hl=pt-BR&amp;ie=UTF8&amp;sll=-14.239424,-53.186502&amp;sspn=66.604122,114.169922&amp;hq=uniam%C3%A9rica+foz&amp;radius=15000&amp;t=m&amp;hnear=&amp;ll=-25.466292,-54.573812&amp;spn=0.023247,0.068665&amp;z=14&amp;output=embed"></iframe>
    </div>
    <div class="details">
        <span class="google_maps icon black"></span><span>Tarquino Joslin dos Santos nº 1000 - Jd. Universitário 
            Foz do Iguaçu - PR - Brasil</span>
        <span class="phone icon black"></span><span>55 45 2105-9000
        </span>
        <span class="e-mail icon black"></span><span class="color">congresso@uniamerica.br</span>
    </div>
</div>