<!DOCTYPE html>
<html lang="en"><head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>Academico - Uniamérica</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <link rel="stylesheet" href="/telefonia1/static/css/bootstrap.css" media="screen">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="../bower_components/bootstrap/assets/js/html5shiv.js"></script>
    <script src="../bower_components/bootstrap/assets/js/respond.min.js"></script>
    <![endif]-->
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
    <script type="text/javascript" src="/telefonia1/script.js"></script>
    <script src="/telefonia1/static/jquery.js"></script>
    <script src="/telefonia1/static/js/bootstrap.js"></script>
    <script src="/telefonia1/static/bootswatch.js"></script>
</head>
<body>
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <a href="http://uniamerica.br/" class="navbar-brand"><img src="/telefonia1/static/img/logo50.gif"> </a>
        <div class="navbar-header">

            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">

            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="themes"><img src="/telefonia1/static/img/menu/academico.png"style="float:left; margin-right: 10px"> Ramais </a>

                </li>
            </ul>

        </div>
    </div>
</div>

<div class="containernovo" style= "margin-top:60px;">
    <h3>Segue instruções do funcionamento da telefonia:</h3>
    <p>- Disque utilizando o teclado numérico e clique em ENTER para completar a ligação (3cxPhone, para o telefone fixo apenas digite);</p>
    <p>- Tecle ** + ramal, para captura chamada de outro ramal;</p>
    <p>- Tecle *8, para captura chamada do grupo;</p>
    <p>- Tecle *2 + ramal, para transferir ligação assistida (pode falar com destinatário antes de transferir);</p>
    <p>- Tecle ## + ramal, para transferir ligação a cega (transfere direto destinatário);</p>
    <p>- Ligação interurbana, digite 0+DDD+TELEFONE (não é necessário informa a operadora).</p>
    <p>Qualquer duvida estaremos a disposição no ramal 9046.</p>
</div>



<div class="containernovo" style= "margin-top:30px;">

    <!-- Main hero unit for a primary marketing message or call to action -->
    <div class="hero-unit">
        <table id="tabela" class="table table">
            <thead>
            <tr style="text-align: center;">
                <th>Nome</th>
                <th>Ramal</th>
                <th>E-mail</th>
                <th>Departamento</th>
            </tr>
            <tr>
                <th><input type="text" id="txtColuna1"/></th>
                <th><input type="text" id="txtColuna2"/></th>
                <th><input type="text" id="txtColuna3"/></th>
                <th><input type="text" id="txtColuna4"/></th>
            </tr>
            </thead>
            <tbody>


            <?php foreach ($this->telefones as $item):  ?>
                <tr>
                    <td><?php echo $item['nome'] ?></td>
                    <td><?php echo $item['ramal'] ?></td>
                     <td><?php echo $item['email'] ?></td>
                    <td><?php echo $item['departamento'] ?></td>
                </tr>
            <?php endforeach; ?>


            </tbody>
        </table>
    </div>


</div> <!-- /container -->

</body>
</html>