<!DOCTYPE html>
<html lang="en">
<head>
    <title>Telefonia</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
    <h2><legend>Telefonia</legend></h2>
    <form name="frmCadastro" id="frmCadastro" action="" method="post" class="form-horizontal">


        <!-- Text input-->
        <div class="form-group">
            <label class="control-label" for="nome">Nome</label>
            <div class="controls">
                <input id="nome" name="nome" placeholder="Nome" class="form-control" required="" type="text">

            </div>
        </div>

        <!-- Text input-->
        <div class="form-group">
            <label class="control-label" for="ramal">Ramal</label>
            <div class="controls">
                <input id="ramal" name="ramal" placeholder="Ramal" class="form-control" required="" type="text">

            </div>
        </div>
        
                <div class="form-group">
            <label class="control-label" for="email">Email</label>
            <div class="controls">
                <input id="ramal" name="email" placeholder="Email" class="form-control" required="" type="text">

            </div>
        </div>

        <!-- Text input-->
        <div class="form-group">
            <label class="control-label" for="departamento">Departamento</label>
            <div class="controls">
                <input id="departamento" name="departamento" placeholder="Departamento" class="form-control" required="" type="text">

            </div>
        </div>

        <button type="submit" class="btn btn-default">Submit</button>
    </form>
</div>

</body>
</html>
