<?php $this->layout()->titulo='O Workshop'; ?>
<?php $this->layout()->description='Saiba mais sobre o Workshop de Biomedicina'; ?>
<div class="container-12">
	<div class="grid-12" style="text-align: justify;">
		<h1 class="title_h1">Workshop de atualização:</h1>
		<h2/>Os aspectos gerais da biomedicina estética e suas aplicações práticas</h2>
		<p>O Biomédico Esteta é o especialista mais qualificado para cuidar da pele saudável e das disfunções estéticas da população. Por meio de tratamentos estéticos a laser e procedimentos minimamente invasivos e medicamentosos, como: preenchimento facial, aplicação de toxina botulínica tipo A e entre outros, o Biomédico Esteta vem ganhando destaque no setor da Saúde Estética, como também no rol das especialidades Biomédicas.</p>
		<p>E como é um segmento totalmente inovador, o curso de Biomedicina da Uniamérica convidou a Palestrante Dra. Ana Carolina Puga, considerada a Mãe da Biomedicina Estética no Brasil, para dividir com os acadêmicos suas experiências profissionais, seu vasto conhecimento adquirido nas mais consagradas estratégias de tratamentos estéticos, aprimoradas em anos de atuação junto à população das mais diversas regiões do Brasil. </p>
		<p>A palestra terá como abordagem também, o mercado de trabalho desse profissional, e informar aos nossos acadêmicos: Os aspectos gerais da biomedicina estética e suas aplicações práticas, o tema central do workshop.</p>
                <p>Local: Faculdade União das Américas
                    <br />
                Horário: 19:30h</p>
        </div>
        
	<div class="box_">
            
            <a href="<?php echo $this->url(array('controller' => 'workshopbio', 'action' => 'inscricoes',), null, true) ?>" title="Inscrições para workshop de Biomedicina Estética">Inscreva-se</a>
        </div>
</div>