a:6:{s:8:"email_de";s:30:"guiade_publicidade@hotmail.com";s:7:"nome_de";s:24:"Curtidas para o facebook";s:8:"telefone";s:8:"30371240";s:7:"assunto";s:24:"Curtidas para o facebook";s:8:"mensagem";s:325:"Curtidas para Facebook...
Mais Curtidas, Mais Clientes, Mais acessos,  Mais Vendas...
Para comprar curtidas, acesse:
http://www.guiapublicidade.com.br/curtidas-facebook.html

conseguimos de 5 mil ate 300 mil curtidas.
100% nacional
Para maiores Inf. somente por telefone.
43-3037-1240 ou Skype: guia.publicidade


";s:5:"chave";s:32:"5ce7598ca3fa6672660a16f94c2875e2";}