a:6:{s:8:"email_de";s:28:"marivane.koschevic@gmail.com";s:7:"nome_de";s:24:"Marivane Turim Koschevic";s:8:"telefone";s:14:"(45) 8414-4460";s:7:"assunto";s:27:"Problemas com a Inscrição";s:8:"mensagem";s:293:"Olá, me inscrevi como ouvinte, mas em virtude da prorrogação do envio de trabalhos vou submeter um artigo, no entanto não consigo me cadastrar novamente como participante, como devo proceder?
Desde já agradeço e aguardo retorno,
Até mais!

Marivane Turim Koschevic
PPGTAMB/UTFPR-MD";s:5:"chave";s:32:"7c6b2d583a89def34a392f3d8ed3390b";}