a:6:{s:8:"email_de";s:19:"portalvde@gmail.com";s:7:"nome_de";s:18:"Wellington Correia";s:8:"telefone";s:14:"(45) 9960-7797";s:7:"assunto";s:23:"Cobertura Jornalística";s:8:"mensagem";s:383:"Prezados (as), bom dia, 

O portal Vida de Estudante solicita credencial para cobertura jornalística do evento. 

Estamos divulgando o evento em nosso portal na forma de cortesia:
http://www.vidadeestudante.com.br/iv-congresso-internacional-de-educacao-da-uniamerica/#.UkWjPYakoR4

Vamos publicar agora a programação.

Um grande abraço.
Wellington Correia
45 9960 7797";s:5:"chave";s:32:"dd5075125cc567f8f0f52da97d3b095d";}