a:6:{s:8:"email_de";s:24:"ivetezelinski@uol.com.br";s:7:"nome_de";s:23:"Ivete Cristina Zelinski";s:8:"telefone";s:14:"(45) 3524-4910";s:7:"assunto";s:11:"inscrição";s:8:"mensagem";s:304:"Desejo saber o valor pra eu participar somente na 5º feira a noite ou seja das 18;30 as 21:30.

                                       Atenciosamente
                                                Ivete Zelinski
                                                            prof. do município de Foz";s:5:"chave";s:32:"ff7c3174b5945fcb9d2d87b008bbd88e";}